apiVersion: v1
kind: Pod
metadata:
  name: disque
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: busybox:1.37
    command: ["sh", "-c", "dd if=/dev/zero of=/tmp/gros bs=1M count=80; echo 'écrit'; sleep 3600"]
    resources:
      limits:
        ephemeral-storage: 50Mi
