apiVersion: v1
kind: Pod
metadata:
  name: gourmand-cpu
spec:
  containers:
  - name: app
    image: busybox:1.37
    command: ["sh", "-c", "while :; do :; done"]
    resources:
      requests:
        cpu: 100m
      limits:
        cpu: 200m
