apiVersion: v1
kind: LimitRange
metadata:
  name: bornes
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: 100m
      memory: 64Mi
    default:
      cpu: 500m
      memory: 128Mi
    max:
      cpu: "1"
      memory: 512Mi
