apiVersion: v1
kind: Pod
metadata:
  name: garanti
spec:
  containers:
  - name: app
    image: busybox:1.37
    command: ["sleep", "3600"]
    resources:
      requests:
        cpu: 250m
        memory: 64Mi
      limits:
        cpu: 250m
        memory: 64Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: extensible
spec:
  containers:
  - name: app
    image: busybox:1.37
    command: ["sleep", "3600"]
    resources:
      requests:
        cpu: 100m
        memory: 32Mi
      limits:
        memory: 128Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: sans-garantie
spec:
  containers:
  - name: app
    image: busybox:1.37
    command: ["sleep", "3600"]
