import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Une catégorie par partie. La classe « partie-N » donne sa couleur de
// conteneur à la catégorie (pastille, lien actif) : voir src/css/custom.css.
const sidebars: SidebarsConfig = {
  cours: [
    {
      type: 'category',
      label: '0 · Démarrer',
      className: 'partie-0',
      collapsed: false,
      items: [
        'demarrer/comment-ce-cours-fonctionne',
        'demarrer/preparer-son-poste',
        'demarrer/versions',
      ],
    },
    {
      type: 'category',
      label: 'I · Utiliser des conteneurs',
      className: 'partie-1',
      collapsed: false,
      link: {type: 'doc', id: 'partie-1/index'},
      items: [
        'partie-1/le-probleme',
        'partie-1/premier-conteneur',
        'partie-1/images',
        'partie-1/dockerfile',
        'partie-1/donnees',
        'partie-1/reseau',
        'partie-1/compose',
        'partie-1/defi',
      ],
    },
    {
      type: 'category',
      label: 'II · Sous le capot',
      className: 'partie-2',
      collapsed: false,
      link: {type: 'doc', id: 'partie-2/index'},
      items: [
        'partie-2/namespaces',
        'partie-2/cgroups',
        'partie-2/overlayfs',
        'partie-2/runtimes',
        'partie-2/securite',
        'partie-2/images-production',
        'partie-2/chaine-approvisionnement',
        'partie-2/defi',
      ],
    },
    {
      type: 'category',
      label: 'III · Premiers pas avec Kubernetes',
      className: 'partie-3',
      collapsed: false,
      link: {type: 'doc', id: 'partie-3/index'},
      items: [
        'partie-3/orchestrateur',
        'partie-3/minikube-kubectl',
        'partie-3/pod',
        'partie-3/declaratif',
        'partie-3/deployment',
        'partie-3/services',
        'partie-3/configuration',
        'partie-3/sante',
        'partie-3/ressources',
        'partie-3/colis-minikube',
        'partie-3/defi',
      ],
    },
    {
      type: 'category',
      label: 'IV · Kubernetes au quotidien',
      className: 'partie-4',
      collapsed: false,
      link: {type: 'doc', id: 'partie-4/index'},
      items: [
        'partie-4/stockage',
        'partie-4/statefulset',
        'partie-4/taches',
        'partie-4/http',
        'partie-4/helm',
        'partie-4/kustomize',
        'partie-4/autoscaling',
        'partie-4/ordonnancement',
        'partie-4/disponibilite',
        'partie-4/defi',
      ],
    },
    {
      type: 'category',
      label: 'V · Anatomie du cluster',
      className: 'partie-5',
      collapsed: false,
      link: {type: 'doc', id: 'partie-5/index'},
      items: [
        'partie-5/api-server',
        'partie-5/etcd',
        'partie-5/controleurs',
        'partie-5/scheduler',
        'partie-5/kubelet',
        'partie-5/reseau-pods',
        'partie-5/services-capot',
        'partie-5/networkpolicies',
        'partie-5/defi',
      ],
    },
    {
      type: 'category',
      label: 'VI · Sécurité',
      className: 'partie-6',
      collapsed: false,
      link: {type: 'doc', id: 'partie-6/index'},
      items: [
        'partie-6/authentification',
        'partie-6/rbac',
        'partie-6/durcir-pods',
        'partie-6/admission',
        'partie-6/secrets',
        'partie-6/images',
        'partie-6/defi',
      ],
    },
    {
      type: 'category',
      label: 'VII · Observer et exploiter',
      className: 'partie-7',
      collapsed: false,
      link: {type: 'doc', id: 'partie-7/index'},
      items: [
        'partie-7/deboguer',
        'partie-7/pannes',
        'partie-7/metriques',
        'partie-7/journaux',
        'partie-7/sauvegarde',
        'partie-7/montee',
        'partie-7/defi',
      ],
    },
    {
      type: 'category',
      label: 'VIII · Étendre Kubernetes et livrer',
      className: 'partie-8',
      collapsed: false,
      link: {type: 'doc', id: 'partie-8/index'},
      items: [
        'partie-8/crd',
        'partie-8/operateur',
        'partie-8/cnpg',
      ],
    },
  ],
};

export default sidebars;
