apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    {{- include "colis.etiquettes" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - name: http
    port: 80
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    {{- include "colis.etiquettes" . | nindent 4 }}
    app.kubernetes.io/name: web
spec:
  replicas: {{ .Values.web.repliques }}
  selector:
    matchLabels:
      app.kubernetes.io/name: web
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "colis.etiquettes" . | nindent 8 }}
        app.kubernetes.io/name: web
    spec:
      containers:
      - name: web
        image: {{ .Values.images.registre }}/{{ .Values.images.web.depot }}:{{ .Values.images.web.etiquette }}
        ports:
        - name: http
          containerPort: 80
        readinessProbe:
          httpGet: {path: /, port: http}
          periodSeconds: 5
        resources:
          {{- toYaml .Values.web.ressources | nindent 10 }}
