#!/usr/bin/env bash
# Chapitre 36 : les contrôleurs. Profil principal (minikube). Namespaces ch36, ch36-bloque, ch36-autre (recréés).
# Arrête ~20 s kube-controller-manager en déplaçant son manifeste statique (remis en place par un trap).
# Crée le ClusterRole et le ClusterRoleBinding cours-lecture-metriques (lecture de /metrics).
cd "$(dirname "$0")"; O=$PWD/out/ch36; rm -rf $O; mkdir -p $O; cp -a ../kits/controleurs $O/m
export PATH=~/.local/opt/cours-k8s/bin:$PATH LC_ALL=C
kubectl config use-context minikube >/dev/null
K="kubectl -n ch36"
remettre() { minikube ssh -- "sudo test -f /etc/kubernetes/kcm.yaml.cours && sudo mv /etc/kubernetes/kcm.yaml.cours /etc/kubernetes/manifests/kube-controller-manager.yaml" >/dev/null 2>&1; }
trap remettre EXIT
H() { local n=$1; shift; echo "### $n : $*"; (cd $O/m && timeout 300 bash -c "$*") 2>&1 | grep -v '^W[0-9]' | grep -v 'docker context\|Docker CLI context' > $O/$n.txt; head -c 6000 $O/$n.txt; }
for n in ch36 ch36-bloque ch36-autre; do kubectl delete namespace $n --wait=true >/dev/null 2>&1; done
kubectl create namespace ch36 >/dev/null
etat="$K get deploy vitrine -o jsonpath='deploy : spec.replicas={.spec.replicas} generation={.metadata.generation} observedGeneration={.status.observedGeneration} prêts={.status.readyReplicas}{\"\\n\"}'; $K get rs -l app=vitrine -o jsonpath='{range .items[*]}rs {.metadata.name} : spec.replicas={.spec.replicas}{\"\\n\"}{end}'; echo \"Pods : \$($K get pods -l app=vitrine --no-headers | wc -l)\""
metriques="T=\$(kubectl -n ch36 create token lecteur-metriques); minikube ssh -- \"curl -sk -H 'Authorization: Bearer \$T' https://127.0.0.1:10257/metrics\" 2>/dev/null | grep -E '^workqueue_(adds_total|depth)\\{' | grep -E 'name=\\\"(deployment|replicaset)\\\"'"

H 01-comptes "kubectl -n kube-system get sa -o name | grep -E 'controller\$' | grep -v -E 'csi-external|snapshot-controller' | sed 's|serviceaccount/||' | column -c 110; kubectl -n kube-system get sa -o name | grep -E 'controller\$' | grep -v -E 'csi-external|snapshot-controller' | wc -l"
H 02-drapeaux "kubectl -n kube-system get pod kube-controller-manager-minikube -o jsonpath='{range .spec.containers[0].command[*]}{@}{\"\\n\"}{end}' | grep -E 'controllers=|leader-elect|use-service-account'; kubectl -n kube-system get lease -o custom-columns=BAIL:.metadata.name,DETENTEUR:.spec.holderIdentity | cut -c1-130"
H 03-vitrine "$K create deployment vitrine --image=registry.k8s.io/e2e-test-images/agnhost:2.61 --replicas=2 -- /agnhost netexec; $K rollout status deploy/vitrine --timeout=90s >/dev/null; $etat"
H 04-metriques "$K create sa lecteur-metriques >/dev/null; kubectl create clusterrole cours-lecture-metriques --verb=get --non-resource-url=/metrics >/dev/null 2>&1; kubectl create clusterrolebinding cours-lecture-metriques --clusterrole=cours-lecture-metriques --serviceaccount=ch36:lecteur-metriques >/dev/null 2>&1; echo '# avant'; $metriques; $K scale deploy vitrine --replicas=3 >/dev/null; $K rollout status deploy/vitrine --timeout=60s >/dev/null; echo '# après scale à 3'; $metriques"
H 05-sans-kcm "minikube ssh -- sudo mv /etc/kubernetes/manifests/kube-controller-manager.yaml /etc/kubernetes/kcm.yaml.cours; for i in \$(seq 1 40); do kubectl -n kube-system get pod kube-controller-manager-minikube >/dev/null 2>&1 || break; sleep 1; done; echo \"gestionnaire de contrôleurs arrêté (Pod disparu après ~\$i s)\"; $K scale deploy vitrine --replicas=4; sleep 10; $etat"
H 06-retour "t=\$(date +%s); minikube ssh -- sudo mv /etc/kubernetes/kcm.yaml.cours /etc/kubernetes/manifests/kube-controller-manager.yaml; for i in \$(seq 1 120); do [ \"\$($K get deploy vitrine -o jsonpath='{.status.readyReplicas}')\" = 4 ] && break; sleep 1; done; echo \"4 Pods prêts \$(( \$(date +%s)-t )) s après la remise en place\"; $etat; kubectl -n kube-system wait --for=condition=Ready pod/kube-controller-manager-minikube --timeout=90s"
H 07-chaine "P=\$($K get pods -l app=vitrine -o name | head -1); $K get \$P -o jsonpath='{.metadata.name} <- {.metadata.ownerReferences[0].kind}/{.metadata.ownerReferences[0].name}{\"\\n\"}'; RS=\$($K get rs -l app=vitrine -o name); $K get \$RS -o jsonpath='{.metadata.name} <- {.metadata.ownerReferences[0].kind}/{.metadata.ownerReferences[0].name}{\"\\n\"}'; $K get \$P -o json | jq '.metadata.ownerReferences'"
H 08-orphelins "RS=\$($K get rs -l app=vitrine -o name); echo \"uid du ReplicaSet : \$($K get \$RS -o jsonpath='{.metadata.uid}')\"; $K get pods -l app=vitrine -o custom-columns=POD:.metadata.name,UID_DU_PROPRIETAIRE:.metadata.ownerReferences[0].uid; $K delete \$RS --cascade=orphan; sleep 3; $K get rs -l app=vitrine -o custom-columns=RS:.metadata.name,UID:.metadata.uid; $K get pods -l app=vitrine -o custom-columns=POD:.metadata.name,UID_DU_PROPRIETAIRE:.metadata.ownerReferences[0].uid,AGE:.metadata.creationTimestamp"
H 09-premier-plan "$K apply -f lent.yaml >/dev/null; $K rollout status deploy/lent --timeout=90s >/dev/null; t=\$(date +%s); $K delete deploy lent --cascade=foreground --wait=false; sleep 1; $K get deploy lent -o jsonpath='deploy lent : deletionTimestamp={.metadata.deletionTimestamp} finalizers={.metadata.finalizers}{\"\\n\"}'; $K get rs -l app=lent -o jsonpath='{range .items[*]}rs {.metadata.name} : deletionTimestamp={.metadata.deletionTimestamp} finalizers={.metadata.finalizers}{\"\\n\"}{end}'; $K get pods -l app=lent; while $K get deploy lent >/dev/null 2>&1; do sleep 0.5; done; echo \"Deployment disparu \$(( \$(date +%s)-t )) s après la demande\""
H 10-finalizer "$K apply -f garde.yaml; $K delete cm garde --wait=false; $K get cm garde -o jsonpath='deletionTimestamp={.metadata.deletionTimestamp} finalizers={.metadata.finalizers}{\"\\n\"}'; $K get cm garde; $K patch cm garde --type=json -p '[{\"op\":\"remove\",\"path\":\"/metadata/finalizers\"}]'; $K get cm garde"
H 11-namespace "kubectl create namespace ch36-bloque; kubectl -n ch36-bloque apply -f garde.yaml >/dev/null; kubectl delete namespace ch36-bloque --wait=false; sleep 6; kubectl get namespace ch36-bloque; kubectl get namespace ch36-bloque -o json | jq -r '.status.conditions[] | select(.status==\"True\") | \"\\(.type) : \\(.message)\"'; kubectl -n ch36-bloque patch cm garde --type=json -p '[{\"op\":\"remove\",\"path\":\"/metadata/finalizers\"}]'; sleep 6; kubectl get namespace ch36-bloque"
H 12-mini "kubectl proxy --port=8011 >/dev/null & P=\$!; sleep 1; python3 -u mini-replicaset.py ch36 > log1.txt 2>&1 & C=\$!; sleep 1
echo '# 1. le souhait : 3 Pods'; $K apply -f vitrine-souhait.yaml; sleep 4; $K get pods -l cours/proprietaire=vitrine
echo '# 2. un Pod supprimé à la main'; V=\$($K get pods -l cours/proprietaire=vitrine -o name | head -1); $K delete \$V --wait=false; sleep 3
echo '# 3. une seule réplique'; $K patch cm vitrine --type=merge -p '{\"data\":{\"repliques\":\"1\"}}'; sleep 3; kill \$C; wait \$C 2>/dev/null
echo '# journal du contrôleur'; cat log1.txt
echo '# 4. contrôleur arrêté, on demande 4 Pods'; $K patch cm vitrine --type=merge -p '{\"data\":{\"repliques\":\"4\"}}'; sleep 3; echo \"Pods (hors Terminating) : \$($K get pods -l cours/proprietaire=vitrine --no-headers | grep -vc Terminating)\"
python3 -u mini-replicaset.py ch36 > log2.txt 2>&1 & C=\$!; sleep 4; kill \$C; wait \$C 2>/dev/null; echo '# journal du contrôleur relancé'; cat log2.txt; echo \"Pods : \$($K get pods -l cours/proprietaire=vitrine --no-headers | grep -vc Terminating)\"
echo '# 5. contrôleur arrêté, on supprime le souhait'; $K get pod -l cours/proprietaire=vitrine -o jsonpath='{.items[0].metadata.ownerReferences}{\"\\n\"}'; $K delete cm vitrine; sleep 4; $K get pods -l cours/proprietaire=vitrine; kill \$P"
H 13-ex-deux "kubectl proxy --port=8011 >/dev/null & P=\$!; sleep 1; python3 -u mini-replicaset.py ch36 > a.txt 2>&1 & A=\$!; python3 -u mini-replicaset.py ch36 > b.txt 2>&1 & B=\$!; sleep 1; $K apply -f vitrine-souhait.yaml >/dev/null; sleep 6; echo \"Pods à la fin : \$($K get pods -l cours/proprietaire=vitrine --no-headers | grep -vc Terminating)\"; kill \$A \$B; wait \$A \$B 2>/dev/null; echo '# copie A'; grep -v démarré a.txt; echo '# copie B'; grep -v démarré b.txt; $K delete cm vitrine >/dev/null; sleep 3; kill \$P"
H 14-ex-orphelin "$K get pods -l app=vitrine -o custom-columns=POD:.metadata.name --no-headers; $K delete deploy vitrine --cascade=orphan; sleep 3; $K get rs,pods -l app=vitrine; $K create deployment vitrine --image=registry.k8s.io/e2e-test-images/agnhost:2.61 --replicas=4 -- /agnhost netexec >/dev/null; sleep 4; $K get rs,pods -l app=vitrine"
H 15-ex-autre-ns "kubectl create namespace ch36-autre >/dev/null; kubectl -n ch36-autre create configmap proprio --from-literal=a=1 >/dev/null; U=\$(kubectl -n ch36-autre get cm proprio -o jsonpath='{.metadata.uid}'); printf 'apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: dependant\n  ownerReferences:\n  - {apiVersion: v1, kind: ConfigMap, name: proprio, uid: %s}\ndata: {a: \"1\"}\n' \$U | $K apply -f -; sleep 8; $K get cm dependant; $K get events --field-selector involvedObject.name=dependant -o custom-columns=RAISON:.reason,MESSAGE:.message --no-headers | cut -c1-200; kubectl delete namespace ch36-autre --wait=false >/dev/null"
H 16-ex-statut "kubectl proxy --port=8011 >/dev/null & P=\$!; sleep 1; python3 -u mini-replicaset-statut.py ch36 > s.txt 2>&1 & S=\$!; sleep 1; $K apply -f vitrine-souhait.yaml >/dev/null; sleep 12; kill \$S; wait \$S 2>/dev/null; grep -v démarré s.txt; $K get cm vitrine -o jsonpath='annotation : {.metadata.annotations.cours/pods}, resourceVersion {.metadata.resourceVersion}{\"\\n\"}'; sleep 5; $K get cm vitrine -o jsonpath='5 s plus tard : resourceVersion {.metadata.resourceVersion}{\"\\n\"}'; $K delete cm vitrine >/dev/null; kill \$P"
