#!/usr/bin/env bash
# Chapitre 24 : TP Colis sur minikube. Namespace « colis » (recréé) ; registre « registre » (localhost:5001) démarré ;
# addon metallb actif. Laisse Colis en marche (http://192.168.49.100/).
# La phase 1 (minikube image load) exige un nœud où le kubelet n'a jamais tiré ces images depuis le registre :
# sinon le contrôle des images déjà téléchargées (KEP 2535) refuse colis-web:1.0 (voir chapitre 24). D'où la remise à zéro.
cd "$(dirname "$0")"; O=$PWD/out/ch24r; rm -rf $O; mkdir -p $O; cp -a ../kits/colis-k8s $O/m
export PATH=~/.local/opt/cours-k8s/bin:$PATH LC_ALL=C
K="kubectl --context minikube -n colis"
H() { local n=$1; shift; echo "### $n : $*"; (cd $O/m && timeout 600 bash -c "$*") 2>&1 | grep -v '^W[0-9]' > $O/$n.txt; head -c 9000 $O/$n.txt; }
docker start registre >/dev/null 2>&1
kubectl --context minikube delete namespace colis --wait=true >/dev/null 2>&1
# Remise à zéro du nœud pour la phase 1 : images de Colis et fiches de tirage du kubelet qui les concernent
# (le kubelet les garde aussi en mémoire, d'où son redémarrage).
minikube ssh -- 'sudo crictl rmi docker.io/library/colis:2.0 docker.io/library/colis-web:1.0 host.minikube.internal:5001/colis/api:2.0 host.minikube.internal:5001/colis/web:1.0; for f in $(sudo grep -l colis -r /var/lib/kubelet/image_manager/pulled); do sudo rm -f $f; done; sudo rm -rf /etc/containerd/certs.d/host.minikube.internal:5001; sudo systemctl restart kubelet' >/dev/null 2>&1
sleep 15; kubectl --context minikube wait --for=condition=Ready node/minikube --timeout=120s >/dev/null
H 00-metallb "kubectl --context minikube apply -f metallb-plage.yaml"
H 01-charger "d=\$(date +%s); minikube image load colis:2.0 colis-web:1.0; echo \"chargement : \$((\$(date +%s)-d)) s\"; minikube ssh -- sudo crictl images | grep -E 'colis'"
H 02-deployer "kubectl --context minikube apply -f 00-namespace.yaml; $K create secret generic colis-db --from-literal=POSTGRES_PASSWORD=\$(head -c 18 /dev/urandom | base64 | tr -d '/+='); kubectl --context minikube apply -f .; d=\$(date +%s); $K wait --for=condition=Available deployment --all --timeout=300s; echo \"disponible en \$((\$(date +%s)-d)) s\"; $K get pods"
H 03-demarrage "$K logs deploy/api --previous 2>&1 | tail -2; $K logs purge | tail -1; $K get events --field-selector involvedObject.kind=Pod --sort-by=.lastTimestamp | grep postgres | grep -E 'Pulled|Unhealthy' | cut -c1-200"
H 04-parcours "IP=\$($K get svc web -o jsonpath='{.status.loadBalancer.ingress[0].ip}'); echo IP=\$IP; curl -s http://\$IP/ | grep -o '<title>.*</title>'; curl -s http://\$IP/api/pret; echo; curl -s -X POST http://\$IP/api/colis -H 'Content-Type: application/json' -d '{\"destinataire\":\"Ada Lovelace\",\"depart\":\"Paris\",\"arrivee\":\"Brest\",\"poids_kg\":2.5}'; echo; sleep 4; curl -s http://\$IP/api/colis/1; echo; $K logs deploy/worker --tail=2; $K delete pod purge >/dev/null; kubectl --context minikube apply -f 50-purge.yaml >/dev/null; $K wait --for=jsonpath='{.status.phase}'=Succeeded pod/purge --timeout=90s >/dev/null; $K logs purge"
H 05-maj "IP=192.168.49.100; ( ok=0; ko=0; fin=\$((\$(date +%s)+45)); while [ \$(date +%s) -lt \$fin ]; do c=\$(curl -s -o /dev/null -m 2 -w '%{http_code}' http://\$IP/api/sante); if [ \"\$c\" = 200 ]; then ok=\$((ok+1)); else ko=\$((ko+1)); fi; sleep 0.1; done; echo \"requêtes réussies : \$ok, échouées : \$ko\" ) > charge.txt & sleep 3; $K rollout restart deployment/api; $K rollout status deployment/api --timeout=120s >/dev/null; wait; cat charge.txt"
H 06-perte "IP=192.168.49.100; curl -s http://\$IP/api/colis | head -c 120; echo; $K delete pod -l app.kubernetes.io/name=postgres --wait=true; $K rollout status deployment/postgres --timeout=120s >/dev/null; sleep 20; $K get pods -l app.kubernetes.io/name=api; curl -s -o /dev/null -w 'site -> %{http_code}\n' http://\$IP/api/colis; P=\$($K get pods -l app.kubernetes.io/name=api -o name | head -1); $K exec \$P -- python -c 'import urllib.request,urllib.error
try: print(urllib.request.urlopen(\"http://127.0.0.1:8000/pret\").read().decode())
except urllib.error.HTTPError as e: print(e.code, e.read().decode())'; $K rollout restart deployment/api deployment/worker; $K rollout status deployment/api --timeout=120s >/dev/null; $K rollout status deployment/worker --timeout=120s >/dev/null; curl -s http://\$IP/api/colis; echo"
H 07-registre "docker tag colis-web:1.0 localhost:5001/colis/web:1.0 && docker push -q localhost:5001/colis/web:1.0; minikube cp hosts.toml /etc/containerd/certs.d/host.minikube.internal:5001/hosts.toml; sed -i 's|image: colis:2.0|image: host.minikube.internal:5001/colis/api:2.0|; s|image: colis-web:1.0|image: host.minikube.internal:5001/colis/web:1.0|' *.yaml; minikube image rm colis:2.0 colis-web:1.0; minikube ssh -- 'sudo crictl rmi host.minikube.internal:5001/colis/api:2.0 host.minikube.internal:5001/colis/web:1.0' >/dev/null 2>&1; $K delete pod purge >/dev/null; kubectl --context minikube apply -f .; for d in api web worker; do $K rollout status deployment/\$d --timeout=180s >/dev/null; done; $K get events --field-selector reason=Pulled --sort-by=.lastTimestamp | grep 'Successfully pulled' | tail -3 | cut -c1-230; curl -s http://192.168.49.100/api/pret; echo"

H 08-sans-hosts "minikube ssh -- 'sudo mv /etc/containerd/certs.d/host.minikube.internal:5001/hosts.toml /tmp/hosts.toml.bak'; kubectl --context minikube run essai-http --restart=Never --image=host.minikube.internal:5001/cours/tampon:1.0.0; sleep 8; kubectl --context minikube get pod essai-http; kubectl --context minikube get events --field-selector involvedObject.name=essai-http,reason=Failed -o jsonpath='{.items[0].message}'; echo; kubectl --context minikube delete pod essai-http; minikube ssh -- 'sudo mv /tmp/hosts.toml.bak /etc/containerd/certs.d/host.minikube.internal:5001/hosts.toml'"
H 09-conflit "minikube image load colis-web:1.0; $K run essai-web --restart=Never --image=colis-web:1.0 --image-pull-policy=IfNotPresent; sleep 8; $K get pod essai-web; $K get events --field-selector involvedObject.name=essai-web,reason=Failed -o jsonpath='{.items[0].message}'; echo; minikube ssh -- sudo crictl images | grep colis-web; $K delete pod essai-web"
