#!/usr/bin/env bash
# Chapitre 31 : l'autoscaling. Namespace ch31 (recréé) ; HPA sur l'API de Colis, VPA 1.8.0 (chart 0.13.0) et
# KEDA 2.21.0 sur le worker. Désinstalle d'abord VPA et KEDA s'ils sont là. Laisse HPA, VPA (Off) et KEDA en place.
cd "$(dirname "$0")"; O=$PWD/out/ch31; rm -rf $O; mkdir -p $O; cp -a ../kits/autoscaling $O/m
export PATH=~/.local/opt/cours-k8s/bin:$PATH LC_ALL=C
KK="kubectl --context minikube"; KC="$KK -n colis"; HELM="helm --kube-context minikube"
H() { local n=$1; shift; echo "### $n : $*"; (cd $O/m && timeout 900 bash -c "$*") 2>&1 | grep -v '^W[0-9]' > $O/$n.txt; head -c 9000 $O/$n.txt; }
$KC delete scaledobject worker --ignore-not-found >/dev/null 2>&1; $KC delete vpa worker --ignore-not-found >/dev/null 2>&1; $KC delete hpa api --ignore-not-found >/dev/null
$HELM uninstall keda -n keda --wait >/dev/null 2>&1; $HELM uninstall vpa -n vpa --wait >/dev/null 2>&1
$KK delete namespace keda vpa ch31 --ignore-not-found --wait=true >/dev/null 2>&1
for c in $($KK get crd -o name | grep -E 'keda.sh|autoscaling.k8s.io'); do $KK delete $c >/dev/null; done
$KK apply -f ../kits/statefulset/colis/30-api.yaml -f ../kits/statefulset/colis/31-worker.yaml >/dev/null
$KC rollout status deploy/api --timeout=180s >/dev/null; $KC rollout status deploy/worker --timeout=180s >/dev/null
$KK create namespace ch31 >/dev/null
etat() { echo "$(date -u +%T) utilisation=$($KC get hpa api -o jsonpath='{.status.currentMetrics[0].resource.current.averageUtilization}')% répliques=$($KC get hpa api -o jsonpath='{.status.currentReplicas}')"; }

H 01-hpa "$KK apply -f hpa-api.yaml; sleep 45; $KC get hpa api; $KC top pod -l app.kubernetes.io/name=api"
H 02-charge "$KK apply -f charge.yaml; t0=\$(date +%s); for i in \$(seq 1 20); do echo \"t=\$(( \$(date +%s)-t0 ))s utilisation=\$($KC get hpa api -o jsonpath='{.status.currentMetrics[0].resource.current.averageUtilization}')% répliques=\$($KC get hpa api -o jsonpath='{.status.currentReplicas}')\"; sleep 10; done; $KC get pods -l app.kubernetes.io/name=api"
H 03-descente "$KK -n ch31 wait --for=condition=Complete job/charge --timeout=300s >/dev/null; t0=\$(date +%s); for i in \$(seq 1 14); do echo \"t=\$(( \$(date +%s)-t0 ))s après la fin de la charge : utilisation=\$($KC get hpa api -o jsonpath='{.status.currentMetrics[0].resource.current.averageUtilization}')% répliques=\$($KC get hpa api -o jsonpath='{.status.currentReplicas}')\"; sleep 10; done; $KC describe hpa api | sed -n '/^Events:/,\$p'; $KK -n ch31 logs job/charge | grep -E '^Code|All done|# target 50%|# target 99%' | head -4"
H 04-vpa "d=\$(date +%s); $HELM install vpa autoscaler/vertical-pod-autoscaler --version 0.13.0 -n vpa --create-namespace -f vpa-valeurs.yaml --wait --timeout 5m 2>&1 | grep -E '^STATUS|rror'; echo \"prêt en \$(( \$(date +%s)-d )) s\"; $KK -n vpa get pods; $KK apply -f vpa-worker.yaml; sleep 90; $KC get vpa worker; $KC get vpa worker -o jsonpath='{.status.recommendation}' | jq -c .; $KC top pod -l app.kubernetes.io/name=worker"
H 05-vpa-auto "P=\$($KC get pods -l app.kubernetes.io/name=worker -o name); echo \"\$P \$($KC get \$P -o jsonpath='{.metadata.uid} restarts={.status.containerStatuses[0].restartCount}')\"; $KC patch vpa worker --type merge -p '{\"spec\":{\"updatePolicy\":{\"updateMode\":\"InPlaceOrRecreate\"}}}'; d=\$(date +%s); for i in \$(seq 1 30); do r=\$($KC get pods -l app.kubernetes.io/name=worker -o jsonpath='{.items[0].spec.containers[0].resources.requests.memory}'); [ \"\$r\" != 96Mi ] && break; sleep 10; done; echo \"changé après \$(( \$(date +%s)-d )) s\"; $KC get pods -l app.kubernetes.io/name=worker -o jsonpath='{range .items[*]}{.metadata.name} {.metadata.uid} restarts={.status.containerStatuses[0].restartCount}{\"\\n\"}{.spec.containers[0].resources}{\"\\n\"}{end}'; $KC get events --field-selector involvedObject.kind=Pod --sort-by=.lastTimestamp | grep -E 'InPlaceResizedByVPA|ResizeCompleted' | tail -2 | cut -c1-160; $KC get deploy worker -o jsonpath='{.spec.template.spec.containers[0].resources}{\"\\n\"}'; $KC patch vpa worker --type merge -p '{\"spec\":{\"updatePolicy\":{\"updateMode\":\"Off\"}}}'"
H 06-keda "d=\$(date +%s); $HELM install keda kedacore/keda --version 2.21.0 -n keda --create-namespace --wait --timeout 5m 2>&1 | grep -E '^STATUS|rror'; echo \"prêt en \$(( \$(date +%s)-d )) s\"; $KK -n keda get pods; $KK apply -f keda-worker.yaml; sleep 45; $KC get scaledobject worker; $KC get hpa; $KC get deploy worker"
H 07-rafale "t0=\$(date +%s); seq 1 100 | xargs -P 10 -I{} curl -s -o /dev/null -X POST http://192.168.49.100/api/colis -H 'Content-Type: application/json' -d '{\"destinataire\":\"Lot {}\",\"depart\":\"Paris\",\"arrivee\":\"Lyon\",\"poids_kg\":1}'; echo \"100 colis créés en \$(( \$(date +%s)-t0 )) s\"; for i in \$(seq 1 30); do f=\$($KC exec deploy/redis -- redis-cli LLEN colis:a-estimer); w=\$($KC get deploy worker -o jsonpath='{.status.readyReplicas}'); r=\$($KC get deploy worker -o jsonpath='{.spec.replicas}'); echo \"t=\$(( \$(date +%s)-t0 ))s file=\$f workers=\${w:-0}/\$r\"; [ \"\$f\" = 0 ] && [ \"\$r\" = 0 ] && break; sleep 5; done; $KC get events --field-selector involvedObject.name=worker --sort-by=.lastTimestamp | grep -E 'KEDAScaleTarget|ScalingReplicaSet' | tail -6 | cut -c1-160"
H 08-memoire "sleep 20; $KK top pod -n vpa; $KK top pod -n keda; docker stats --no-stream --format '{{.MemUsage}}' minikube"
