#!/usr/bin/env bash
# Chapitre 35 : etcd. Profil principal (minikube), namespace ch35 (recréé), clé de test /cours/compteur
# (supprimée à la fin). Trio etcd local dans Docker (cours-etcd-1..3, réseau cours-etcd), recréé, laissé en marche.
cd "$(dirname "$0")"; O=$PWD/out/ch35; rm -rf $O; mkdir -p $O; cp -a ../kits/etcd $O/m
export PATH=~/.local/opt/cours-k8s/bin:$PATH LC_ALL=C
kubectl config use-context minikube >/dev/null
K="kubectl -n ch35"
H() { local n=$1; shift; echo "### $n : $*"; (cd $O/m && timeout 300 bash -c "source ./etcd-minikube.sh; EP=cours-etcd-1:2379,cours-etcd-2:2379,cours-etcd-3:2379; $*") 2>&1 | grep -v '^W[0-9]' | grep -v '^{\"level\"' > $O/$n.txt; head -c 6000 $O/$n.txt; }
kubectl delete namespace ch35 --wait=true >/dev/null 2>&1; kubectl create namespace ch35 >/dev/null
(cd ../kits/etcd && ./trio.sh supprimer >/dev/null 2>&1)

H 01-statut "E endpoint status -w simple | awk -F', ' '{print \$1, \"| base\", \$5, \"dont\", \$6, \"utiles | leader\", \$9, \"| terme\", \$11, \"| index\", \$12}'; E member list -w simple"
H 02-cles "E get /registry --prefix --keys-only | grep -c /; E get /registry --prefix --keys-only | grep / | awk -F/ '{print \$3}' | sort | uniq -c | sort -rn | head -8; E get /registry --prefix --keys-only | grep -E '^/registry/(deployments/colis|pods/colis/postgres|keda.sh|namespaces/colis\$)'"
H 03-creer "$K create configmap reglages --from-literal=couleur=bleu; E get /registry/configmaps/ch35/reglages -w json | jq -c '{revision: .header.revision} + (.kvs[0] | {create_revision, mod_revision, version})'; $K get cm reglages -o jsonpath='{.metadata.resourceVersion}{\"\\n\"}'"
H 04-valeur "E get /registry/configmaps/ch35/reglages --print-value-only | od -c | head -14"
H 05-modifier "$K patch cm reglages --type=merge -p '{\"data\":{\"couleur\":\"vert\"}}'; E get /registry/configmaps/ch35/reglages -w json | jq -c '{revision: .header.revision} + (.kvs[0] | {create_revision, mod_revision, version})'; $K get cm reglages -o jsonpath='{.metadata.resourceVersion}{\"\\n\"}'; R=\$(E get /registry/configmaps/ch35/reglages -w json | jq '.kvs[0].create_revision'); echo \"lecture à la révision \$R :\"; E get /registry/configmaps/ch35/reglages --rev=\$R --print-value-only | strings | grep -A1 '^couleur' | tail -1"
H 06-compacte "E get /registry/configmaps/ch35/reglages --rev=100"
H 07-crd "E get /registry/keda.sh/scaledobjects/colis/worker --print-value-only | head -c 150; echo"
H 08-secret "$K create secret generic motdepasse --from-literal=motdepasse=Tr3sS3cret; E get /registry/secrets/ch35/motdepasse --print-value-only | strings | grep -B1 Tr3sS3cret"
H 09-baux "E lease list | head -1; C1=\$(E get /registry/events/colis --prefix --keys-only | grep / | head -1); echo \$C1; L=\$(E get \$C1 -w json | jq -r '.kvs[0].lease'); E lease timetolive \$(printf '%x' \$L)"
H 10-watch "(timeout 12 kubectl -n kube-system exec etcd-minikube -- etcdctl --cacert=\$C/ca.crt --cert=\$C/server.crt --key=\$C/server.key watch /registry/configmaps/ch35/ --prefix -w json > ew.txt 2>/dev/null) & sleep 2; $K create configmap temoin --from-literal=a=1 >/dev/null; $K label cm temoin vu=oui >/dev/null; $K delete cm temoin >/dev/null; wait; jq -c '.Events[] | {type: (if .type == 1 then \"DELETE\" else \"PUT\" end), cle: (.kv.key|@base64d), mod_revision: .kv.mod_revision, version: (.kv.version // 0)}' ew.txt"
H 11-txn "E put /cours/compteur 1; M=\$(E get /cours/compteur -w json | jq '.kvs[0].mod_revision'); echo \"lu à la révision \$M\"; txn() { printf 'mod(\"/cours/compteur\") = \"%s\"\n\nput /cours/compteur %s\n\nget /cours/compteur\n\n' \$1 \$2 | E txn -w simple; }; echo '# écrivain A'; txn \$M 2; echo '# écrivain B'; txn \$M 3; E del /cours/compteur"
H 12-direct "V='{\"apiVersion\":\"v1\",\"kind\":\"ConfigMap\",\"metadata\":{\"name\":\"Reglages_1\",\"namespace\":\"ch35\",\"uid\":\"00000000-0000-0000-0000-000000000001\",\"creationTimestamp\":\"2026-01-01T00:00:00Z\"},\"data\":{\"origine\":\"etcdctl\"}}'; E put /registry/configmaps/ch35/Reglages_1 \"\$V\"; sleep 1; $K get cm; $K delete cm Reglages_1"
H 13-cache "minikube ssh -- curl -s 127.0.0.1:2381/metrics | grep -E '^etcd_debugging_mvcc_watcher_total|^etcd_disk_wal_fsync_duration_seconds_(count|sum)'; kubectl get --raw /metrics | grep -E '^apiserver_longrunning_requests\\{' | grep WATCH | awk '{s+=\$NF} END{print \"watches servis par l API server :\", s}'"
H 14-defrag "E endpoint status -w simple | awk -F', ' '{print \$1, \"| base\", \$5, \"dont\", \$6, \"utiles | leader\", \$9, \"| terme\", \$11, \"| index\", \$12}'; E defrag; E endpoint status -w simple | awk -F', ' '{print \$1, \"| base\", \$5, \"dont\", \$6, \"utiles | leader\", \$9, \"| terme\", \$11, \"| index\", \$12}'"
H 15-trio "./trio.sh demarrer; sleep 4; docker exec cours-etcd-1 etcdctl --endpoints=\$EP endpoint status -w simple | awk -F', ' '{print \$1, \"| base\", \$5, \"dont\", \$6, \"utiles | leader\", \$9, \"| terme\", \$11, \"| index\", \$12}'; docker stats --no-stream --format '{{.Name}} {{.MemUsage}}' cours-etcd-1 cours-etcd-2 cours-etcd-3"
H 16-repliquer "docker exec cours-etcd-2 etcdctl --endpoints=cours-etcd-2:2379 put /colis/1 enregistré; docker exec cours-etcd-3 etcdctl --endpoints=cours-etcd-3:2379 get /colis/1"
H 17-leader "L=\$(docker exec cours-etcd-1 etcdctl --endpoints=\$EP endpoint status -w simple | awk -F', ' '\$9==\"true\"{print \$1}' | cut -d: -f1); echo \"leader : \$L\"; T=\$(date -u +%Y-%m-%dT%H:%M:%S.%NZ); docker kill \$L; echo \"tué à \${T:11:12}\"; sleep 4; for m in cours-etcd-1 cours-etcd-2 cours-etcd-3; do [ \$m = \$L ] && continue; echo \"# journal de \$m\"; docker logs --since \$T \$m 2>&1 | jq -r 'select(.msg|test(\"lost leader|became leader|elected leader|starting a new election|became candidate|became follower\")) | \"\\(.ts[11:23]) \\(.msg)\"'; done; S=\$(docker ps --format '{{.Names}}' | grep cours-etcd | sort | head -1); docker exec \$S etcdctl --endpoints=\$(docker ps --format '{{.Names}}:2379' | grep cours-etcd | sort | paste -sd,) endpoint status -w simple | cut -d, -f1,9,11,12; docker exec \$S etcdctl --endpoints=\$S:2379 put /colis/2 estimé"
H 18-quorum "L=\$(docker exec \$(docker ps --format '{{.Names}}' | grep cours-etcd | head -1) etcdctl --endpoints=\$(docker ps --format '{{.Names}}:2379' | grep cours-etcd | sort | paste -sd,) endpoint status -w simple | awk -F', ' '\$9==\"true\"{print \$1}' | cut -d: -f1); echo \"arrêt du nouveau leader : \$L\"; T=\$(date -u +%Y-%m-%dT%H:%M:%S.%NZ); docker kill \$L; echo \"tué à \${T:11:12}\"; S=\$(docker ps --format '{{.Names}}' | grep cours-etcd); echo \"seul survivant : \$S\"; t=\$(date +%s); docker exec \$S etcdctl --endpoints=\$S:2379 --command-timeout=5s put /colis/3 livré; echo \"code \$? après \$(( \$(date +%s)-t )) s\"; docker exec \$S etcdctl --endpoints=\$S:2379 --command-timeout=5s get /colis --prefix; echo \"code \$?\"; docker exec \$S etcdctl --endpoints=\$S:2379 get /colis --prefix --consistency=s; echo \"code \$?\"; docker logs --since \$T \$S 2>&1 | jq -r 'select(.msg|test(\"election|lost leader|became|stepped down|quorum\")) | \"\\(.ts[11:23]) \\(.msg)\"' | head -6"
H 19-retour "docker start cours-etcd-1 cours-etcd-2 cours-etcd-3 >/dev/null; sleep 4; docker exec cours-etcd-1 etcdctl --endpoints=\$EP endpoint status -w simple | cut -d, -f1,9,11,12; docker exec cours-etcd-1 etcdctl --endpoints=\$EP put /colis/3 livré; docker exec cours-etcd-1 etcdctl --endpoints=\$EP get /colis --prefix"
H 20-transfert "L=\$(docker exec cours-etcd-1 etcdctl --endpoints=\$EP endpoint status -w simple | awk -F', ' '\$9==\"true\"{print \$1}' | cut -d: -f1); echo \"leader : \$L\"; T=\$(date -u +%Y-%m-%dT%H:%M:%S.%NZ); docker stop \$L >/dev/null; echo \"arrêt propre (SIGTERM) à \${T:11:12}\"; sleep 2; docker logs --since \$T \$L 2>&1 | jq -r 'select(.msg|test(\"transfer|leadership\")) | \"\\(.ts[11:23]) \\(.msg)\"' | head -4; for m in cours-etcd-1 cours-etcd-2 cours-etcd-3; do [ \$m = \$L ] && continue; docker logs --since \$T \$m 2>&1 | jq -r 'select(.msg|test(\"MsgTimeoutNow|became leader\")) | \"\\(.ts[11:23]) \\(.msg)\"'; done; docker start \$L >/dev/null"
H 21-ex-ecritures "$K apply -f - >/dev/null <<'Y'
apiVersion: apps/v1
kind: Deployment
metadata: {name: vitrine}
spec:
  replicas: 1
  selector: {matchLabels: {app: vitrine}}
  template:
    metadata: {labels: {app: vitrine}}
    spec:
      containers:
      - {name: web, image: registry.k8s.io/e2e-test-images/agnhost:2.61, args: [netexec], resources: {requests: {cpu: 10m, memory: 16Mi}}}
Y
$K rollout status deploy/vitrine --timeout=90s >/dev/null; sleep 3
(timeout 15 kubectl -n kube-system exec etcd-minikube -- etcdctl --cacert=\$C/ca.crt --cert=\$C/server.crt --key=\$C/server.key watch /registry/ --prefix -w json > tout.txt 2>/dev/null) & sleep 2; $K scale deploy vitrine --replicas=2 >/dev/null; wait
jq -r '.Events[] | (.kv.key|@base64d) as \$k | select(\$k|test(\"/ch35/\")) | \"\\(.kv.mod_revision) \\(if .type == 1 then \"DELETE\" else \"PUT   \" end) \\(\$k)\"' tout.txt | sed -E 's/(vitrine-[a-z0-9]+-)[a-z0-9]{5}/\\1xxxxx/; s/\\.[0-9a-f]{16}\$/.../'"
H 22-ex-secret "E get /registry/secrets/colis/colis-db --print-value-only | strings | grep -A1 POSTGRES_PASSWORD | tail -1 | cut -c1-6; echo '(tronqué)'"
H 23-ex-suiveur "L=\$(docker exec cours-etcd-1 etcdctl --endpoints=\$EP endpoint status -w simple | awk -F', ' '\$9==\"false\"{print \$1}' | head -1 | cut -d: -f1); echo \"suiveur arrêté : \$L\"; docker kill \$L >/dev/null; S=\$(docker ps --format '{{.Names}}' | grep cours-etcd | head -1); for i in 1 2 3 4 5; do docker exec \$S etcdctl --endpoints=\$S:2379 put /rattrapage/\$i x >/dev/null; done; docker exec \$S etcdctl --endpoints=\$(docker ps --format '{{.Names}}:2379' | grep cours-etcd | sort | paste -sd,) endpoint status -w simple | cut -d, -f1,9,11,12; docker start \$L >/dev/null; sleep 3; docker exec \$L etcdctl --endpoints=\$EP endpoint status -w simple | cut -d, -f1,9,11,12; docker exec \$L etcdctl --endpoints=\$L:2379 get /rattrapage --prefix --keys-only --consistency=s | grep -c /"
H 24-ex-compteur "$K create configmap compteur --from-literal=valeur=0 >/dev/null; kubectl proxy --port=8011 >/dev/null & P=\$!; sleep 1; python3 compteur.py A 20 & python3 compteur.py B 20 & wait %2 %3; kill \$P; $K get cm compteur -o jsonpath='valeur finale : {.data.valeur}{\"\\n\"}'"
H 25-ex-compteur-sans "$K delete cm compteur >/dev/null; $K create configmap compteur --from-literal=valeur=0 >/dev/null; kubectl proxy --port=8011 >/dev/null & P=\$!; sleep 1; python3 compteur.py A 20 sans-version & python3 compteur.py B 20 sans-version & wait %2 %3; kill \$P; $K get cm compteur -o jsonpath='valeur finale : {.data.valeur}{\"\\n\"}'"
