#!/usr/bin/env bash
# Chapitre 29 : Helm. Namespaces « ch29 » et « colis-helm » (recréés). Suppose la passerelle du chapitre 28.
# Pousse le chart de Colis (0.1.0 sans « keep » sur le Secret, puis 0.1.1) dans le registre localhost:5001.
# Laisse Colis installé par Helm dans colis-helm, publié sous colis-helm.local.
cd "$(dirname "$0")"; O=$PWD/out/ch29; rm -rf $O; mkdir -p $O; cp -a ../kits/helm $O/m
export PATH=~/.local/opt/cours-k8s/bin:$PATH LC_ALL=C
KK="kubectl --context minikube"; K="$KK -n ch29"; KH="$KK -n colis-helm"; HELM="helm --kube-context minikube"; H="$HELM -n ch29"; HH="$HELM -n colis-helm"
IP=192.168.49.102
H() { local n=$1; shift; echo "### $n : $*"; (cd $O/m && timeout 900 bash -c "$*") 2>&1 | grep -v '^W[0-9]' > $O/$n.txt; head -c 9000 $O/$n.txt; }
$HH uninstall colis --wait >/dev/null 2>&1; $H uninstall demo piege --wait >/dev/null 2>&1
$KK delete namespace ch29 colis-helm --wait=true >/dev/null 2>&1
$KK create namespace ch29 >/dev/null; $KK create namespace colis-helm >/dev/null; $KK label namespace colis-helm passerelle=principale >/dev/null
# les variantes du chart : 0.1.0 (Secret sans keep) et « piège » (mot de passe tiré à chaque rendu)
cd $O/m && cp -a colis colis-0.1.0 && sed -i 's/^version: 0.1.1 /version: 0.1.0 /' colis-0.1.0/Chart.yaml && sed -i '/helm.sh\/resource-policy: keep/d; /^  annotations:$/d' colis-0.1.0/templates/secret.yaml
cp -a colis piege && printf 'apiVersion: v1\nkind: Secret\nmetadata:\n  name: colis-db\ntype: Opaque\ndata:\n  POSTGRES_PASSWORD: {{ randAlphaNum 24 | b64enc }}\n' > piege/templates/secret.yaml; cd - >/dev/null

H 01-podinfo "$H install demo oci://ghcr.io/stefanprodan/charts/podinfo --version 6.14.1 2>&1 | grep -v '^Pulled\|^Digest'; $K rollout status deploy/demo-podinfo --timeout=120s >/dev/null; $H list; $K get deploy,svc,pods; $K exec deploy/demo-podinfo -- wget -qO- localhost:9898 | jq -c '{hostname,version,message}'"
H 02-maj "$H upgrade demo oci://ghcr.io/stefanprodan/charts/podinfo --version 6.15.0 -f podinfo-valeurs.yaml 2>&1 | grep -E '^Release|^STATUS|^REVISION'; $K rollout status deploy/demo-podinfo --timeout=120s >/dev/null; $K get pods; $K exec deploy/demo-podinfo -- wget -qO- localhost:9898 | jq -c '{hostname,version,message}'; $H history demo; $H get values demo"
H 03-retour "$H rollback demo 1; $K rollout status deploy/demo-podinfo --timeout=120s >/dev/null; $H history demo; $K get pods; $K exec deploy/demo-podinfo -- wget -qO- localhost:9898 | jq -c '{version,message}'"
H 04-stockage "$K get secrets; $K get secret sh.helm.release.v1.demo.v3 -o jsonpath='{.metadata.labels}{\"\\n\"}'; $K get secret sh.helm.release.v1.demo.v3 -o jsonpath='{.data.release}' | base64 -d | base64 -d | gunzip | jq -c '{name, version, statut: .info.status, chart: .chart.metadata.version, apply_method, cles: keys}'; $K get deploy demo-podinfo -o jsonpath='{.metadata.labels}{\"\\n\"}{.metadata.annotations}{\"\\n\"}'; $H get manifest demo | grep -E '^# Source'; $H uninstall demo --wait"
H 05-lint "helm lint colis; helm template essai colis -n colis-helm --set passerelle.activee=true | grep -E '^# Source|^kind:' | paste - -; helm template essai colis --set api.repliques=5 | grep -A3 'name: api\$' | grep replicas; helm template essai colis | grep -A2 'kind: Secret' | head -3; helm template essai colis | grep POSTGRES_PASSWORD: "
H 06-piege "$H install piege piege --set sauvegarde.avantMiseAJour=false --set api.repliques=1 --set web.repliques=1 --wait --timeout 5m 2>&1 | grep -E '^STATUS|^REVISION'; $K get secret colis-db -o jsonpath='{.data.POSTGRES_PASSWORD}' | base64 -d; echo; $H upgrade piege piege --set sauvegarde.avantMiseAJour=false --set api.repliques=2 --set web.repliques=1 2>&1 | grep -E '^STATUS|^REVISION'; $K get secret colis-db -o jsonpath='{.data.POSTGRES_PASSWORD}' | base64 -d; echo; sleep 45; $K get pods -l app.kubernetes.io/name=api --sort-by=.metadata.creationTimestamp; P=\$($K get pods -l app.kubernetes.io/name=api --sort-by=.metadata.creationTimestamp -o name | tail -1); $K logs \$P --previous 2>/dev/null | tail -1; $H uninstall piege --wait >/dev/null; $K delete pvc --all >/dev/null"
H 07-installation "d=\$(date +%s); $HH install colis ./colis-0.1.0 --set passerelle.activee=true --set passerelle.hote=colis-helm.local --wait --timeout 5m; echo \"installé en \$(( \$(date +%s)-d )) s\"; $KH get pods,pvc; $HH test colis 2>&1 | grep -E 'TEST SUITE|Phase'; $KH logs colis-test-pret; echo; curl -s -H 'Host: colis-helm.local' http://$IP/api/sante; echo"
H 08-maj "curl -s -X POST http://$IP/api/colis -H 'Host: colis-helm.local' -H 'Content-Type: application/json' -d '{\"destinataire\":\"Frances Allen\",\"depart\":\"Paris\",\"arrivee\":\"Nantes\",\"poids_kg\":1.1}' | jq -c '{id,destinataire}'; m1=\$($KH get secret colis-db -o jsonpath='{.data.POSTGRES_PASSWORD}'); c1=\$($KH get deploy worker -o jsonpath='{.spec.template.metadata.annotations.checksum/config}'); $HH upgrade colis ./colis-0.1.0 --reuse-values --set api.repliques=3 --set worker.pause=0.2 --wait --timeout 5m 2>&1 | grep -E '^STATUS|^REVISION'; $KH get jobs; $KH logs job/sauvegarde-avant-maj; m2=\$($KH get secret colis-db -o jsonpath='{.data.POSTGRES_PASSWORD}'); [ \"\$m1\" = \"\$m2\" ] && echo 'mot de passe inchangé'; c2=\$($KH get deploy worker -o jsonpath='{.spec.template.metadata.annotations.checksum/config}'); echo \"checksum : \${c1:0:12}... -> \${c2:0:12}...\"; $KH get deploy api worker; $HH history colis; $HH get values colis; curl -s -H 'Host: colis-helm.local' http://$IP/api/colis | jq -c '[.[] | {id,destinataire}]'"
H 09-retour "$HH rollback colis 1 --wait 2>&1 | tail -1; $HH history colis; $KH get deploy api worker"
H 10-oci "cd colis-0.1.0 && helm package . -d .. && cd .. && helm push colis-0.1.0.tgz oci://localhost:5001/charts --plain-http; curl -s localhost:5001/v2/charts/colis/tags/list; echo; helm show chart oci://localhost:5001/charts/colis --version 0.1.0 --plain-http 2>/dev/null"
H 11-desinstaller "$HH uninstall colis --wait; sleep 20; $KH get all,pvc,secret"
H 12-reinstaller "$KH delete pod colis-test-pret --ignore-not-found; $KH delete job sauvegarde-avant-maj --ignore-not-found; $HH install colis oci://localhost:5001/charts/colis --version 0.1.0 --plain-http --set passerelle.activee=true --set passerelle.hote=colis-helm.local --wait --timeout 90s 2>&1 | grep -E '^Pulled|^STATUS|rror'; $KH get pods -l app.kubernetes.io/name=api; P=\$($KH get pods -l app.kubernetes.io/name=api -o name | head -1); $KH logs \$P --previous 2>/dev/null | tail -1; $KH logs postgres-0 | grep -m1 'Skipping initialization'"
H 13-reparer "M=\$($KH get secret colis-db -o jsonpath='{.data.POSTGRES_PASSWORD}' | base64 -d); $KH exec postgres-0 -- psql -U colis -d colis -c \"ALTER USER colis PASSWORD '\$M';\"; $KH rollout status deploy/api --timeout=180s | tail -1; curl -s -H 'Host: colis-helm.local' http://$IP/api/colis | jq -c '[.[] | {id,destinataire}]'"
H 14-keep "helm package colis -d . >/dev/null && helm push colis-0.1.1.tgz oci://localhost:5001/charts --plain-http 2>&1 | head -1; $HH upgrade colis oci://localhost:5001/charts/colis --version 0.1.1 --plain-http --reuse-values --wait --timeout 3m 2>&1 | grep -E '^STATUS|^REVISION'; $HH history colis; $HH uninstall colis --wait; sleep 15; $KH get secret,pvc; $KH delete job sauvegarde-avant-maj --ignore-not-found; $KH delete pod colis-test-pret --ignore-not-found; $HH install colis oci://localhost:5001/charts/colis --version 0.1.1 --plain-http --set passerelle.activee=true --set passerelle.hote=colis-helm.local --wait --timeout 3m 2>&1 | grep -E '^STATUS|rror'; $KH get pods -l app.kubernetes.io/name=api; curl -s -H 'Host: colis-helm.local' http://$IP/api/colis | jq -c '[.[] | {id,destinataire}]'; $HH list"
