#!/usr/bin/env bash
# Chapitre 25 : le stockage. Namespace « ch25 » (recréé), PV disque-1 et StorageClass csi-attente (recréés).
# Suppose les addons storage-provisioner, volumesnapshots et csi-hostpath-driver actifs, et Colis du ch. 24 en marche.
# Laisse ch25 en place, et Colis avec PostgreSQL sur un PVC.
cd "$(dirname "$0")"; O=$PWD/out/ch25; rm -rf $O; mkdir -p $O; cp -a ../kits/stockage $O/m
export PATH=~/.local/opt/cours-k8s/bin:$PATH LC_ALL=C
K="kubectl --context minikube -n ch25"; KC="kubectl --context minikube -n colis"; KK="kubectl --context minikube"
H() { local n=$1; shift; echo "### $n : $*"; (cd $O/m && timeout 600 bash -c "$*") 2>&1 | grep -v '^W[0-9]' > $O/$n.txt; head -c 9000 $O/$n.txt; }
$KK delete namespace ch25 --wait=true >/dev/null 2>&1
$KK delete pv disque-1 storageclass csi-attente --ignore-not-found >/dev/null 2>&1
minikube ssh -- 'sudo rm -rf /data/disque-1' >/dev/null 2>&1
$KK create namespace ch25 >/dev/null

# emptyDir
H 01-brouillon "$K apply -f brouillon.yaml; $K wait --for=condition=Ready pod/brouillon --timeout=120s; sleep 12; $K exec brouillon -c lecteur -- cat /lecture/journal.txt; $K exec brouillon -c lecteur -- sh -c 'echo test > /lecture/essai'"
H 02-noeud "U=\$($K get pod brouillon -o jsonpath='{.metadata.uid}'); echo \$U; minikube ssh -- \"sudo ls -l /var/lib/kubelet/pods/\$U/volumes/ /var/lib/kubelet/pods/\$U/volumes/kubernetes.io~empty-dir/brouillon\"; $K exec brouillon -c ecrivain -- sh -c 'mount | grep brouillon'"
H 03-redemarrage "$K exec brouillon -c ecrivain -- touch /brouillon/stop; sleep 8; $K get pod brouillon; $K exec brouillon -c lecteur -- sh -c 'wc -l < /lecture/journal.txt; head -2 /lecture/journal.txt'"
H 04-depassement "U=\$($K get pod brouillon -o jsonpath='{.metadata.uid}'); d=\$(date +%s); $K exec brouillon -c ecrivain -- dd if=/dev/zero of=/brouillon/gros bs=1M count=60 2>&1 | tail -1; for i in \$(seq 1 40); do s=\$($K get pod brouillon -o jsonpath='{.status.phase}'); [ \"\$s\" != Running ] && break; sleep 3; done; echo \"expulsé après \$(( \$(date +%s)-d )) s\"; $K get pod brouillon; $K get pod brouillon -o jsonpath='{.status.reason}{\": \"}{.status.message}{\"\\n\"}'; minikube ssh -- \"sudo ls -A /var/lib/kubelet/pods/\$U/volumes/kubernetes.io~empty-dir/brouillon\"; $K delete pod brouillon; sleep 3; minikube ssh -- \"sudo test -d /var/lib/kubelet/pods/\$U && echo toujours là || echo dossier du Pod supprimé\""
H 05-memoire "$K apply -f memoire.yaml; $K wait --for=condition=Ready pod/memoire --timeout=60s; $K exec memoire -- df -h /rapide; $K exec memoire -- dd if=/dev/zero of=/rapide/a bs=1M count=40 2>&1 | tail -1; $K exec memoire -- dd if=/dev/zero of=/rapide/b bs=1M count=40; echo \"code \$?\"; sleep 3; $K get pod memoire; $K get pod memoire -o jsonpath='{.status.containerStatuses[0].lastState.terminated.reason}{\"\\n\"}'; $K exec memoire -- ls -l /rapide; $K delete pod memoire"
H 06-hote "$K apply -f hote.yaml; $K wait --for=condition=Ready pod/hote --timeout=60s; $K exec hote -- cat /hote/etc/hostname; $K exec hote -- head -3 /hote/etc/shadow; $K exec hote -- sh -c 'ls /hote/var/lib/kubelet/pods | wc -l'; $K delete pod hote"
# PV et PVC statiques
H 07-pv "$KK apply -f pv-statique.yaml; $KK get pv disque-1; $K apply -f pvc-statique.yaml; sleep 2; $K get pvc donnees; $KK get pv disque-1; $KK get pv disque-1 -o jsonpath='{.spec.claimRef}'; echo"
H 08-carnet "$K apply -f carnet.yaml; $K wait --for=condition=Ready pod/carnet --timeout=60s; $K delete pod carnet; $K apply -f carnet.yaml; $K wait --for=condition=Ready pod/carnet --timeout=60s; $K logs carnet; minikube ssh -- 'ls -l /data/disque-1'"
H 09-protection "$K delete pvc donnees --wait=false; sleep 2; $K get pvc donnees; $K get pvc donnees -o jsonpath='{.metadata.finalizers}{\"\\n\"}'; $K delete pod carnet; sleep 3; $K get pvc donnees; $KK get pv disque-1"
H 10-reprise "$K apply -f pvc-statique.yaml; sleep 5; $K get pvc donnees; $K describe pvc donnees | sed -n '/^Events:/,\$p'; $KK patch pv disque-1 --type json -p '[{\"op\":\"remove\",\"path\":\"/spec/claimRef\"}]'; d=\$(date +%s); until [ \"\$($K get pvc donnees -o jsonpath='{.status.phase}')\" = Bound ]; do sleep 1; done; echo \"liée après \$(( \$(date +%s)-d )) s\"; $KK get pv disque-1; $K get pvc donnees; $K apply -f carnet.yaml; $K wait --for=condition=Ready pod/carnet --timeout=60s; $K logs carnet"
# Provisionnement dynamique
H 11-classe "$KK get storageclass; $KK get storageclass standard -o jsonpath='{.provisioner} {.reclaimPolicy} {.volumeBindingMode}{\"\\n\"}{.metadata.annotations.storageclass\\.kubernetes\\.io/is-default-class}{\"\\n\"}'"
H 12-dynamique "$K apply -f pvc-dynamique.yaml; sleep 3; $K get pvc petit; V=\$($K get pvc petit -o jsonpath='{.spec.volumeName}'); $KK get pv \$V; $KK get pv \$V -o jsonpath='{.spec.hostPath.path}{\"\\n\"}'; $K apply -f remplisseur.yaml; $K wait --for=condition=Ready pod/remplisseur --timeout=60s; $K logs remplisseur; $K delete pod remplisseur; $K delete pvc petit; sleep 5; $KK get pv \$V; minikube ssh -- 'ls /tmp/hostpath-provisioner/ch25/'"
H 13-rapide "$K apply -f pvc-rapide.yaml; sed 's/claimName: petit/claimName: rapide/; s/name: remplisseur\$/name: attente/' remplisseur.yaml | $K apply -f -; sleep 5; $K get pvc rapide; $K describe pvc rapide | sed -n '/^Events:/,\$p'; $K get pod attente; $K describe pod attente | sed -n '/^Events:/,\$p'; $K delete pod attente; $K delete pvc rapide"
# CSI
H 14-csi "$KK -n kube-system get pods | grep -E 'csi|snapshot'; $KK get csidriver; $KK get csinode minikube -o jsonpath='{.spec.drivers[*].name}{\"\\n\"}'; P=\$($KK -n kube-system get pods -o name | grep csi-hostpathplugin); $KK -n kube-system get \$P -o jsonpath='{range .spec.containers[*]}{.name}{\"\\n\"}{end}'; minikube ssh -- 'sudo ls /var/lib/kubelet/plugins/csi-hostpath /var/lib/kubelet/plugins_registry'"
H 15-attente "$KK apply -f classe-csi.yaml; sed -n '1,/^---/p' journal.yaml | head -n -1 | $K apply -f -; sleep 4; $K get pvc journal; $K describe pvc journal | sed -n '/^Events:/,\$p'; $K apply -f journal.yaml; $K wait --for=condition=Ready pod/journal --timeout=120s; $K get pvc journal; $K get events --field-selector involvedObject.name=journal --sort-by=.metadata.resourceVersion -o custom-columns=OBJET:.involvedObject.kind,RAISON:.reason,SOURCE:.source.component | sed 's/_csi-hostpathplugin.*//'; $K get pvc journal -o jsonpath='{.metadata.annotations.volume\\.kubernetes\\.io/selected-node}{\"\\n\"}'; V=\$($K get pvc journal -o jsonpath='{.spec.volumeName}'); $KK get pv \$V -o jsonpath='{.spec.csi.driver} {.spec.csi.volumeHandle}{\"\\n\"}'; minikube ssh -- 'sudo ls /var/lib/csi-hostpath-data/'"
H 16-partage "$K apply -f journal-bis.yaml; $K wait --for=condition=Ready pod/journal-bis --timeout=60s; $K get pods journal journal-bis -o wide | cut -c1-90; $K exec journal -- cat /journal/journal.txt; $K apply -f unique.yaml; sleep 10; $K get pods premier second; $K describe pod second | sed -n '/^Events:/,\$p'"
H 17-agrandir "$K patch pvc journal -p '{\"spec\":{\"resources\":{\"requests\":{\"storage\":\"200Mi\"}}}}'; d=\$(date +%s); for i in \$(seq 1 90); do c=\$($K get pvc journal -o jsonpath='{.status.capacity.storage}'); [ \"\$c\" = 200Mi ] && break; sleep 2; done; echo \"capacité \$c après \$(( \$(date +%s)-d )) s\"; $K get pvc journal; $K get events --field-selector involvedObject.kind=PersistentVolumeClaim,involvedObject.name=journal --sort-by=.metadata.resourceVersion -o custom-columns=RAISON:.reason,MESSAGE:.message | tail -4 | cut -c1-160"
H 18-instantane "$K exec journal -- sh -c 'echo \"\$(date -u +%T) avant instantané\" >> /journal/journal.txt'; $K apply -f instantane.yaml; $K wait --for=jsonpath='{.status.readyToUse}'=true volumesnapshot/journal-1 --timeout=60s; $K get volumesnapshot journal-1; $K exec journal -- sh -c 'echo \"\$(date -u +%T) après instantané\" >> /journal/journal.txt'; minikube ssh -- 'sudo ls /var/lib/csi-hostpath-data/'"
H 19-restaure-trop-petit "sed '0,/storage: 200Mi.*/s//storage: 100Mi/' restaure.yaml | $K apply -f -; sleep 8; $K get pvc journal-restaure; $K get events --field-selector involvedObject.name=journal-restaure,reason=ProvisioningFailed -o jsonpath='{.items[0].message}'; echo; $K delete pod lecteur-restaure; $K delete pvc journal-restaure"
H 20-restaure "$K apply -f restaure.yaml; $K wait --for=condition=Ready pod/lecteur-restaure --timeout=120s; $K logs lecteur-restaure; $K get pvc journal-restaure"
# Colis
# Colis repart de l'état du chapitre 24 : PostgreSQL sur emptyDir, sans PVC.
$KK apply -f ../kits/colis-k8s/20-postgres.yaml >/dev/null; $KC delete pvc postgres-donnees --ignore-not-found >/dev/null; $KC rollout status deployment/postgres --timeout=180s >/dev/null
$KC rollout restart deployment/api deployment/worker >/dev/null; $KC rollout status deployment/api --timeout=180s >/dev/null
H 21-colis "$KK apply -f colis/20-postgres.yaml; $KC rollout status deployment/postgres --timeout=180s; $KC get pvc; $KC rollout restart deployment/api deployment/worker; $KC rollout status deployment/api --timeout=120s; $KC rollout status deployment/worker --timeout=120s; curl -s http://192.168.49.100/api/colis; echo"
H 22-colis-perte "IP=192.168.49.100; curl -s -X POST http://\$IP/api/colis -H 'Content-Type: application/json' -d '{\"destinataire\":\"Margaret Hamilton\",\"depart\":\"Nantes\",\"arrivee\":\"Strasbourg\",\"poids_kg\":3.1}' >/dev/null; sleep 4; curl -s http://\$IP/api/colis | jq -c '[.[] | {id, destinataire, statut}]'; $KC delete pod -l app.kubernetes.io/name=postgres --wait=true; $KC rollout status deployment/postgres --timeout=120s; $KC rollout restart deployment/api deployment/worker; $KC rollout status deployment/api --timeout=120s; $KC rollout status deployment/worker --timeout=120s; sleep 5; curl -s http://\$IP/api/colis | jq -c '[.[] | {id, destinataire, statut}]'; minikube ssh -- 'sudo du -sh /tmp/hostpath-provisioner/colis/postgres-donnees; sudo ls /tmp/hostpath-provisioner/colis/postgres-donnees/18/docker | head -4'"
