#!/usr/bin/env bash
# Chapitre 38 : le kubelet et le CRI. Profil « deux-noeuds » (2 nœuds). Namespace ch38 (recréé).
# Applique d'abord le nettoyage des chapitres 32, 33 et 37 (namespaces ch32, ch33, ch37 et leurs objets de cluster).
# Arrête ~60 s le kubelet de deux-noeuds-m02 (relancé par un trap). Dépose puis retire un Pod statique sur m02.
cd "$(dirname "$0")"; O=$PWD/out/ch38; rm -rf $O; mkdir -p $O; cp -a ../kits/kubelet $O/m
export PATH=~/.local/opt/cours-k8s/bin:$PATH LC_ALL=C
kubectl config use-context deux-noeuds >/dev/null
K="kubectl -n ch38"
N() { minikube ssh -p deux-noeuds -n deux-noeuds-m02 -- "$@" 2>/dev/null | tr -d '\r'; }
export -f N
trap 'N "sudo systemctl start kubelet" >/dev/null; N "sudo rm -f /etc/kubernetes/manifests/statique.yaml" >/dev/null' EXIT
H() { local n=$1; shift; echo "### $n : $*"; (cd $O/m && timeout 300 bash -c "$*") 2>&1 | grep -v '^W[0-9]' | grep -v 'docker context\|Docker CLI context' > $O/$n.txt; head -c 6000 $O/$n.txt; }
# nettoyage des chapitres précédents, tel que leurs pages le demandent
for n in ch32 ch33 ch37 ch38; do kubectl delete namespace $n --ignore-not-found >/dev/null 2>&1; done
while kubectl get namespace ch32 ch33 ch37 ch38 2>/dev/null | grep -q ch3; do sleep 2; done
kubectl delete clusterrolebinding cours-ordonnanceur-serre cours-ordonnanceur-serre-volumes cours-lecture-metriques-ch37 >/dev/null 2>&1; kubectl delete clusterrole cours-lecture-metriques >/dev/null 2>&1; kubectl -n kube-system delete rolebinding cours-ordonnanceur-serre >/dev/null 2>&1
kubectl label node deux-noeuds-m02 disque- >/dev/null 2>&1; kubectl uncordon deux-noeuds deux-noeuds-m02 >/dev/null 2>&1
kubectl create namespace ch38 >/dev/null
etat="echo \"+\$(( \$(date +%s)-t0 )) s : nœud \$(kubectl get node deux-noeuds-m02 -o jsonpath='{.status.conditions[?(@.type==\"Ready\")].status}'), taints \$(kubectl get node deux-noeuds-m02 -o jsonpath='{.spec.taints[*].key}'), Pod suivi \$($K get pod suivi -o jsonpath='{.status.phase}/{.status.conditions[?(@.type==\"Ready\")].status}')\""

H 01-kubelet "N 'ps -o pid,rss,args -C kubelet' | cut -c1-160; kubectl get --raw /api/v1/nodes/deux-noeuds-m02/proxy/configz | jq '.kubeletconfig | {staticPodPath, fileCheckFrequency, syncFrequency, nodeStatusUpdateFrequency, cgroupDriver, containerRuntimeEndpoint, maxPods, evictionHard}'"
H 02-cri "N 'sudo crictl version'"
H 03-suivi "$K apply -f suivi.yaml; $K wait --for=condition=Ready pod/suivi --timeout=90s >/dev/null; $K get pod suivi -o jsonpath='uid du Pod : {.metadata.uid}{\"\\n\"}'; N 'sudo crictl pods --name suivi --state ready'; N 'sudo crictl ps --name web --pod \$(sudo crictl pods --name suivi --state ready -q)'"
H 04-bac-a-sable "S=\$(N 'sudo crictl pods --name suivi --state ready -q'); N \"sudo crictl inspectp \$S\" | jq '{image: .info.image, pid: .info.pid, netns: (.info.runtimeSpec.linux.namespaces[] | select(.type==\"network\") | .path), cgroupsPath: .info.runtimeSpec.linux.cgroupsPath}'"
H 05-processus "S=\$(N 'sudo crictl pods --name suivi --state ready -q'); C=\$(N \"sudo crictl ps --name web --pod \$S -q\"); PP=\$(N \"sudo crictl inspectp \$S\" | jq -r .info.pid); PC=\$(N \"sudo crictl inspect \$C\" | jq -r .info.pid); echo \"pause : \$PP, web : \$PC\"; N \"ps -o pid,ppid,user,rss,args -p \$PP,\$PC,\\\$(ps -o ppid= -p \$PP | tr -d ' ')\" | cut -c1-150; echo '# espaces de noms'; N \"for t in net ipc uts pid mnt; do printf '%-4s pause=%s web=%s\\n' \\\$t \\\$(sudo readlink /proc/\$PP/ns/\\\$t) \\\$(sudo readlink /proc/\$PC/ns/\\\$t); done\""
H 06-cgroups "S=\$(N 'sudo crictl pods --name suivi --state ready -q'); C=\$(N \"sudo crictl ps --name web --pod \$S -q\"); PC=\$(N \"sudo crictl inspect \$C\" | jq -r .info.pid); CG=\$(N \"cat /proc/\$PC/cgroup\"); echo \"\$CG\"; D=\${CG#0::}; for f in cpu.max cpu.weight memory.max memory.current; do echo \"\$f : \$(N \"cat /sys/fs/cgroup\$D/\$f\")\"; done; echo '# classes de QoS'; N 'ls -d /sys/fs/cgroup/kubepods.slice/*.slice' | sed 's|/sys/fs/cgroup/||'"
H 07-tuer "S=\$(N 'sudo crictl pods --name suivi --state ready -q'); C=\$(N \"sudo crictl ps --name web --pod \$S -q\"); PC=\$(N \"sudo crictl inspect \$C\" | jq -r .info.pid); t0=\$(date +%s.%N); N \"sudo kill -9 \$PC\"; for i in \$(seq 1 100); do [ \"\$($K get pod suivi -o jsonpath='{.status.containerStatuses[0].restartCount}')\" = 1 ] && break; sleep 0.2; done; printf 'restartCount passé à 1 en %.1f s\\n' \$(echo \"\$(date +%s.%N)-\$t0\" | bc); $K get pod suivi -o jsonpath='{.status.containerStatuses[0].lastState}{\"\\n\"}' | jq -c .; N \"sudo crictl ps -a --pod \$S\""
H 08-vue-kubelet "kubectl get --raw /api/v1/nodes/deux-noeuds-m02/proxy/pods | jq -r '.items[] | \"\\(.metadata.namespace)/\\(.metadata.name)\"'"
H 09-statique "minikube cp -p deux-noeuds statique.yaml deux-noeuds-m02:/etc/kubernetes/manifests/statique.yaml >/dev/null 2>&1; for i in \$(seq 1 40); do $K get pod statique-deux-noeuds-m02 >/dev/null 2>&1 && break; sleep 1; done; sleep 4; $K get pods -o wide | grep -E 'NAME|statique' | cut -c1-110; $K get pod statique-deux-noeuds-m02 -o json | jq '{annotations: .metadata.annotations, ownerReferences: .metadata.ownerReferences}'"
H 10-miroir "S1=\$(N 'sudo crictl pods --name statique -q'); $K delete pod statique-deux-noeuds-m02; sleep 3; $K get pods | grep -E 'NAME|statique'; S2=\$(N 'sudo crictl pods --name statique -q --state ready'); echo \"bac à sable avant : \${S1:0:13}, après : \${S2:0:13}\"; N 'sudo rm /etc/kubernetes/manifests/statique.yaml'; for i in \$(seq 1 40); do $K get pod statique-deux-noeuds-m02 >/dev/null 2>&1 || break; sleep 1; done; echo \"fichier retiré : Pod disparu après ~\$i s\"; $K get pods | grep statique || echo 'plus de Pod statique'"
H 11-sans-kubelet "IP=\$($K get pod suivi -o jsonpath='{.status.podIP}'); kubectl -n kube-node-lease get lease deux-noeuds-m02 -o jsonpath='bail renouvelé à {.spec.renewTime}, durée {.spec.leaseDurationSeconds} s{\"\\n\"}'; t0=\$(date +%s); N 'sudo systemctl stop kubelet'; echo \"kubelet arrêté à \$(date -u +%T)\"; for i in 1 2 3 4 5 6 7; do $etat; sleep 10; done; kubectl -n kube-node-lease get lease deux-noeuds-m02 -o jsonpath='bail renouvelé à {.spec.renewTime}{\"\\n\"}'; kubectl get node deux-noeuds-m02 -o jsonpath='{range .status.conditions[*]}{.type}={.status} ({.reason}){\"\\n\"}{end}'; echo '# sur le nœud'; N 'sudo crictl ps --name web --state running' | grep suivi | cut -c1-120; N \"curl -s -m 2 http://\$IP:8080/hostname\"; echo"
H 12-retour "t1=\$(date +%s); N 'sudo systemctl start kubelet'; kubectl wait --for=condition=Ready node/deux-noeuds-m02 --timeout=60s >/dev/null; echo \"nœud Ready \$(( \$(date +%s)-t1 )) s après le redémarrage\"; sleep 10; t0=\$t1; $etat; $K get pod suivi -o jsonpath='restartCount={.status.containerStatuses[0].restartCount}{\"\\n\"}'"
H 13-ex-stats "kubectl proxy --port=8011 >/dev/null & P=\$!; sleep 1; python3 stats.py deux-noeuds-m02; kill \$P"
H 14-ex-modifier "minikube cp -p deux-noeuds statique.yaml deux-noeuds-m02:/etc/kubernetes/manifests/statique.yaml >/dev/null 2>&1; for i in \$(seq 1 40); do $K get pod statique-deux-noeuds-m02 >/dev/null 2>&1 && break; sleep 1; done; sleep 5; $K get pod statique-deux-noeuds-m02 -o jsonpath='hash {.metadata.annotations.kubernetes\\.io/config\\.hash}, args {.spec.containers[0].args}, uid {.metadata.uid}{\"\\n\"}'; t0=\$(date +%s); N 'sudo sed -i s/8080/9090/ /etc/kubernetes/manifests/statique.yaml'; for i in \$(seq 1 60); do $K get pod statique-deux-noeuds-m02 -o jsonpath='{.spec.containers[0].args}' 2>/dev/null | grep -q 9090 && break; sleep 1; done; echo \"nouvelle version visible après \$(( \$(date +%s)-t0 )) s\"; sleep 3; $K get pod statique-deux-noeuds-m02 -o jsonpath='hash {.metadata.annotations.kubernetes\\.io/config\\.hash}, args {.spec.containers[0].args}, uid {.metadata.uid}{\"\\n\"}'; N 'sudo crictl pods --name statique' | head -3; N 'sudo rm /etc/kubernetes/manifests/statique.yaml'"
H 15-ex-journaux "UID1=\$($K get pod suivi -o jsonpath='{.metadata.uid}'); N \"sudo ls /var/log/pods/ch38_suivi_\$UID1/web/\"; $K logs suivi --previous | tail -2; N \"sudo tail -2 /var/log/pods/ch38_suivi_\$UID1/web/0.log\""
H 16-ex-pause "S=\$(N 'sudo crictl pods --name suivi --state ready -q'); PP=\$(N \"sudo crictl inspectp \$S\" | jq -r .info.pid); echo \"avant : bac à sable \${S:0:13}, IP \$($K get pod suivi -o jsonpath='{.status.podIP}'), restartCount \$($K get pod suivi -o jsonpath='{.status.containerStatuses[0].restartCount}')\"; N \"sudo kill -9 \$PP\"; sleep 15; S2=\$(N 'sudo crictl pods --name suivi --state ready -q'); echo \"après : bac à sable \${S2:0:13}, IP \$($K get pod suivi -o jsonpath='{.status.podIP}'), restartCount \$($K get pod suivi -o jsonpath='{.status.containerStatuses[0].restartCount}')\"; $K get events --field-selector involvedObject.name=suivi -o custom-columns=RAISON:.reason,MESSAGE:.message --no-headers | grep -E 'SandboxChanged|Killing' | tail -2"
