#!/usr/bin/env bash
# Chapitre 28 : exposer en HTTP. Repart de zéro : désinstalle Envoy Gateway, cert-manager et leurs CRD, puis
# rejoue Ingress (addon ingress, désactivé ensuite), Gateway API 1.6.2, Envoy Gateway 1.9.1, cert-manager 1.21.2.
# Laisse la passerelle principale (192.168.49.102) servir Colis en HTTPS sur colis.local.
cd "$(dirname "$0")"; O=$PWD/out/ch28; rm -rf $O; mkdir -p $O; cp -a ../kits/http $O/m
export PATH=~/.local/opt/cours-k8s/bin:$PATH LC_ALL=C
KK="kubectl --context minikube"; KC="$KK -n colis"; HELM="helm --kube-context minikube"
H() { local n=$1; shift; echo "### $n : $*"; (cd $O/m && timeout 900 bash -c "$*") 2>&1 | grep -v '^W[0-9]' > $O/$n.txt; head -c 9000 $O/$n.txt; }
# --- remise à zéro
$KK delete namespace vitrine passerelle --ignore-not-found --wait=true >/dev/null 2>&1
$KC delete -f ../kits/http/colis/route-tls.yaml -f ../kits/http/colis/api-canari.yaml -f ../kits/http/colis/autorisation-vitrine.yaml --ignore-not-found >/dev/null 2>&1
$KC delete ingress colis colis-api --ignore-not-found >/dev/null 2>&1
$KK delete gatewayclass envoy --ignore-not-found >/dev/null 2>&1
$KK delete clusterissuer autosigne colis-ca --ignore-not-found >/dev/null 2>&1
$HELM uninstall eg -n envoy-gateway-system >/dev/null 2>&1; $HELM uninstall cert-manager -n cert-manager >/dev/null 2>&1
$KK delete namespace envoy-gateway-system cert-manager --ignore-not-found --wait=true >/dev/null 2>&1
for c in $($KK get crd -o name | grep -E 'gateway.networking.k8s.io|gateway.networking.x-k8s.io|gateway.envoyproxy.io|cert-manager.io'); do $KK delete $c >/dev/null; done
$KK delete validatingadmissionpolicybinding,validatingadmissionpolicy safe-upgrades.gateway.networking.k8s.io --ignore-not-found >/dev/null 2>&1
$KK label namespace colis passerelle- >/dev/null 2>&1
minikube addons disable ingress >/dev/null 2>&1

H 01-ingress "d=\$(date +%s); minikube addons enable ingress 2>&1 | tail -1; $KK -n ingress-nginx wait --for=condition=Ready pod -l app.kubernetes.io/component=controller --timeout=300s >/dev/null; echo \"prêt en \$(( \$(date +%s)-d )) s\"; $KK -n ingress-nginx get pods,svc; $KK get ingressclass; $KK -n ingress-nginx get pod -l app.kubernetes.io/component=controller -o jsonpath='{.items[0].spec.containers[0].ports}{\"\\n\"}'"
H 02-ingress-colis "$KK apply -f ingress-colis.yaml; sleep 15; $KC get ingress; curl -s -H 'Host: colis.local' http://192.168.49.2/ | grep -o '<title>.*</title>'; curl -s -H 'Host: colis.local' http://192.168.49.2/api/sante; echo; curl -s -o /dev/null -w 'autre hôte : %{http_code}\n' -H 'Host: autre.local' http://192.168.49.2/"
H 03-ingress-api "$KK apply -f ingress-api.yaml; sleep 8; curl -s -i -H 'Host: colis.local' http://192.168.49.2/api/sante | grep -iE '^HTTP|^server'; $KK -n ingress-nginx logs deploy/ingress-nginx-controller --tail=1 | cut -c1-200; $KC delete ingress colis colis-api; minikube addons disable ingress 2>&1 | tail -1"
H 04-crd "$KK apply --server-side -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.6.2/standard-install.yaml; $KK get crd -o custom-columns=NOM:.metadata.name,VERSION:.metadata.annotations.gateway\\.networking\\.k8s\\.io/bundle-version,CANAL:.metadata.annotations.gateway\\.networking\\.k8s\\.io/channel | grep -E 'NOM|gateway'"
H 05-helm-conflit "$HELM install eg oci://docker.io/envoyproxy/gateway-helm --version v1.9.1 -n envoy-gateway-system --create-namespace 2>&1 | grep -v '^Pulled\|^Digest' | tail -5; $HELM list -A; $KK get crd -o name | grep x-k8s"
H 06-envoy "for c in \$($KK get crd -o name | grep gateway.networking.x-k8s.io); do $KK delete \$c; done; $HELM template eg-crds oci://docker.io/envoyproxy/gateway-crds-helm --version v1.9.1 --set crds.envoyGateway.enabled=true 2>/dev/null | $KK apply --server-side -f -; d=\$(date +%s); $HELM install eg oci://docker.io/envoyproxy/gateway-helm --version v1.9.1 -n envoy-gateway-system --create-namespace --skip-crds 2>&1 | grep -E '^NAME|^STATUS'; $KK -n envoy-gateway-system wait --for=condition=Available deployment/envoy-gateway --timeout=300s >/dev/null; echo \"prêt en \$(( \$(date +%s)-d )) s\"; $KK -n envoy-gateway-system get pods"
H 07-passerelle "$KK apply -f passerelle.yaml; $KK -n passerelle wait --for=condition=Programmed gateway/principale --timeout=180s >/dev/null; $KK get gatewayclass; $KK -n passerelle get gateway principale; $KK -n envoy-gateway-system get pods,svc -l gateway.envoyproxy.io/owning-gateway-name=principale"
H 08-route-refusee "$KK apply -f colis/route.yaml; sleep 5; $KC get httproute colis -o jsonpath='{range .status.parents[0].conditions[*]}{.type}={.status} {.reason}: {.message}{\"\\n\"}{end}'; curl -s -o /dev/null -w '%{http_code}\n' -H 'Host: colis.local' http://192.168.49.102/"
H 09-route "$KK label namespace colis passerelle=principale; sleep 5; $KC get httproute colis -o jsonpath='{range .status.parents[0].conditions[*]}{.type}={.status} {.reason}{\"\\n\"}{end}'; $KC get httproute; IP=192.168.49.102; curl -s -H 'Host: colis.local' http://\$IP/ | grep -o '<title>.*</title>'; curl -s -i -H 'Host: colis.local' http://\$IP/api/sante | grep -iE '^HTTP|^server|statut'; curl -s -o /dev/null -w 'autre hôte : %{http_code}\n' -H 'Host: autre.local' http://\$IP/"
H 10-canari "$KK apply -f colis/api-canari.yaml; $KC rollout status deploy/api-canari --timeout=120s >/dev/null; $KK apply -f colis/route-canari.yaml; sleep 5; for i in \$(seq 1 200); do curl -s -H 'Host: colis.local' http://192.168.49.102/api/sante | jq -r .version; done | sort | uniq -c; for i in 1 2 3; do curl -s -H 'Host: colis.local' -H 'X-Canari: oui' http://192.168.49.102/api/sante | jq -r .version; done | uniq -c"
H 11-vitrine "$KK apply -f vitrine.yaml; sleep 5; $KK -n vitrine get httproute vitrine -o jsonpath='{range .status.parents[0].conditions[*]}{.type}={.status} {.reason}: {.message}{\"\\n\"}{end}'; curl -s -o /dev/null -w '%{http_code}\n' -H 'Host: vitrine.local' http://192.168.49.102/; $KK apply -f colis/autorisation-vitrine.yaml; sleep 5; $KK -n vitrine get httproute vitrine -o jsonpath='{range .status.parents[0].conditions[*]}{.type}={.status} {.reason}{\"\\n\"}{end}'; curl -s -H 'Host: vitrine.local' http://192.168.49.102/ | grep -o '<title>.*</title>'"
H 12-cert-manager "d=\$(date +%s); $HELM install cert-manager oci://quay.io/jetstack/charts/cert-manager --version v1.21.2 -n cert-manager --create-namespace -f cert-manager-valeurs.yaml 2>&1 | grep -E '^NAME|^STATUS'; $KK -n cert-manager wait --for=condition=Available deployment --all --timeout=300s >/dev/null; echo \"prêt en \$(( \$(date +%s)-d )) s\"; $KK -n cert-manager get pods; $KK -n cert-manager logs deploy/cert-manager | grep -m1 'certificate-shim'"
H 13-autorite "$KK apply -f autorite.yaml; $KK -n cert-manager wait --for=condition=Ready certificate/colis-ca --timeout=60s; $KK get clusterissuer"
H 14-https "$KK apply -f passerelle-tls.yaml -f colis/route-tls.yaml; $KK -n passerelle wait --for=condition=Ready certificate/colis-tls --timeout=120s; $KK -n passerelle get certificate,certificaterequest; $KK -n passerelle get certificate colis-tls -o jsonpath='{.metadata.ownerReferences[0].kind}/{.metadata.ownerReferences[0].name}{\"\\n\"}{.status.notBefore} {.status.notAfter} {.status.renewalTime}{\"\\n\"}'; $KK -n passerelle get secret colis-tls -o jsonpath='{.type}{\"\\n\"}'; $KK -n cert-manager get secret colis-ca -o jsonpath='{.data.ca\\.crt}' | base64 -d > ca.crt; sleep 5; IP=192.168.49.102; curl -s -i -H 'Host: colis.local' http://\$IP/api/sante | head -2; curl -s --cacert ca.crt --resolve colis.local:443:\$IP https://colis.local/api/sante; echo; curl -s -o /dev/null -w 'sans --cacert : code curl %{exitcode}\n' --resolve colis.local:443:\$IP https://colis.local/; curl -s --resolve colis.local:443:\$IP https://colis.local/ 2>&1 >/dev/null; curl -sS --resolve colis.local:443:\$IP https://colis.local/ 2>&1 | head -1; echo | openssl s_client -connect \$IP:443 -servername colis.local 2>/dev/null | openssl x509 -noout -subject -issuer -dates -ext subjectAltName"
H 15-renouvellement "IP=192.168.49.102; s1=\$(echo | openssl s_client -connect \$IP:443 -servername colis.local 2>/dev/null | openssl x509 -noout -serial); echo \"avant : \$s1\"; ( fin=\$((\$(date +%s)+20)); ok=0; ko=0; while [ \$(date +%s) -lt \$fin ]; do if curl -s -o /dev/null -m 2 --cacert ca.crt --resolve colis.local:443:\$IP https://colis.local/api/sante; then ok=\$((ok+1)); else ko=\$((ko+1)); fi; sleep 0.1; done; echo \"pendant le renouvellement : \$ok réussies, \$ko échouées\" ) & sleep 3; $KK -n passerelle patch certificate colis-tls --subresource=status --type=merge -p \"{\\\"status\\\":{\\\"conditions\\\":[{\\\"type\\\":\\\"Ready\\\",\\\"status\\\":\\\"True\\\",\\\"reason\\\":\\\"Ready\\\",\\\"message\\\":\\\"Certificate is up to date and has not expired\\\",\\\"lastTransitionTime\\\":\\\"\$(date -u +%Y-%m-%dT%H:%M:%SZ)\\\"},{\\\"type\\\":\\\"Issuing\\\",\\\"status\\\":\\\"True\\\",\\\"reason\\\":\\\"ManuallyTriggered\\\",\\\"message\\\":\\\"Certificate re-issuance manually triggered\\\",\\\"lastTransitionTime\\\":\\\"\$(date -u +%Y-%m-%dT%H:%M:%SZ)\\\"}]}}\"; wait; echo \"après : \$(echo | openssl s_client -connect \$IP:443 -servername colis.local 2>/dev/null | openssl x509 -noout -serial)\"; $KK -n passerelle get certificate colis-tls -o jsonpath='révision {.status.revision}{\"\\n\"}'"
H 16-trou "IP=192.168.49.102; s1=\$(echo | openssl s_client -connect \$IP:443 -servername colis.local 2>/dev/null | openssl x509 -noout -serial); $KK -n passerelle delete secret colis-tls; d=\$(date +%s%N); while true; do s=\$(echo | timeout 2 openssl s_client -connect \$IP:443 -servername colis.local 2>/dev/null | openssl x509 -noout -serial 2>/dev/null); [ -n \"\$s\" ] && [ \"\$s\" != \"\$s1\" ] && break; sleep 0.2; done; echo \"sans certificat pendant \$(( (\$(date +%s%N)-d)/1000000 )) ms\""
H 17-memoire "sleep 30; $KK top pod -n envoy-gateway-system; $KK top pod -n cert-manager; docker stats --no-stream --format '{{.MemUsage}}' minikube"
