#!/usr/bin/env bash
# Chapitre 37 : le scheduler. Profil « deux-noeuds » (2 nœuds, profil principal arrêté). Namespace ch37 (recréé).
# Crée : ClusterRoleBindings cours-ordonnanceur-serre(-volumes), RoleBinding kube-system/cours-ordonnanceur-serre,
# ClusterRole cours-lecture-metriques et ClusterRoleBinding cours-lecture-metriques-ch37. Étiquette disque=ssd sur m02.
cd "$(dirname "$0")"; O=$PWD/out/ch37; rm -rf $O; mkdir -p $O; cp -a ../kits/scheduler $O/m
export PATH=~/.local/opt/cours-k8s/bin:$PATH LC_ALL=C
kubectl config use-context deux-noeuds >/dev/null
K="kubectl -n ch37"
H() { local n=$1; shift; echo "### $n : $*"; (cd $O/m && timeout 300 bash -c "$*") 2>&1 | grep -v '^W[0-9]' | grep -v 'docker context\|Docker CLI context' > $O/$n.txt; head -c 6000 $O/$n.txt; }
kubectl delete namespace ch37 --wait=true >/dev/null 2>&1; kubectl label node deux-noeuds-m02 disque- >/dev/null 2>&1; kubectl uncordon deux-noeuds-m02 >/dev/null 2>&1
kubectl delete clusterrolebinding cours-ordonnanceur-serre cours-ordonnanceur-serre-volumes cours-lecture-metriques-ch37 >/dev/null 2>&1; kubectl -n kube-system delete rolebinding cours-ordonnanceur-serre >/dev/null 2>&1
kubectl create namespace ch37 >/dev/null
metriques="T=\$($K create token lecteur-metriques); minikube ssh -p deux-noeuds -- \"curl -sk -H 'Authorization: Bearer \$T' https://127.0.0.1:10259/metrics\" 2>/dev/null | grep -E '^scheduler_pending_pods|^scheduler_schedule_attempts_total'"

H 01-drapeaux "kubectl -n kube-system get pod kube-scheduler-deux-noeuds -o jsonpath='{range .spec.containers[0].command[*]}{@}{\"\\n\"}{end}'"
H 02-config "$K run config-defaut --image=registry.k8s.io/kube-scheduler:v1.37.0 --restart=Never --command -- kube-scheduler --write-config-to=/dev/stdout >/dev/null; $K wait --for=jsonpath='{.status.phase}'=Succeeded pod/config-defaut --timeout=60s >/dev/null; $K logs config-defaut | sed -n '/^apiVersion/,\$p' > config.yaml; grep -E 'percentageOfNodesToScore|podInitialBackoffSeconds|podMaxBackoffSeconds|schedulerName' config.yaml; sed -n '/multiPoint:/,/permit:/p' config.yaml | grep -E 'name:|weight:' | paste - - | awk '{print \$3, \"poids\", \$5}'; sed -n '/name: NodeResourcesFit\$/,+0p;/NodeResourcesFitArgs/,/type:/p' config.yaml; $K delete pod config-defaut >/dev/null"
H 03-noeuds "kubectl get nodes -o custom-columns=NOEUD:.metadata.name,CPU:.status.allocatable.cpu,MEMOIRE:.status.allocatable.memory; for n in deux-noeuds deux-noeuds-m02; do echo \"\$n : \$(kubectl describe node \$n | grep -E '^  cpu ' | awk '{print \$2, \$3}') de processeur déjà demandé\"; done"
H 04-serre-v1 "kubectl apply -f ordonnanceur-serre.yaml; $K rollout status deploy/ordonnanceur-serre --timeout=120s >/dev/null; $K apply -f pods-test.yaml; $K rollout status deploy/etale --timeout=120s >/dev/null; $K rollout status deploy/serre --timeout=120s >/dev/null; $K get pods -l 'app in (etale,serre)' -o custom-columns=POD:.metadata.name,NOEUD:.spec.nodeName --sort-by=.metadata.name"
H 05-journal-v1 "for P in \$($K logs deploy/ordonnanceur-serre | grep -o 'Attempting to schedule pod\" pod=\"ch37/serre-[a-z0-9-]*' | head -2 | sed 's/.*ch37\\///'); do echo \"# Pod \$P\"; $K logs deploy/ordonnanceur-serre | grep \"pod=\\\"ch37/\$P\\\"\" | grep -E 'Plugin scored|final score|Attempting to bind' | sed -E 's/^I[0-9 :.]+ +1 [a-z_]+\\.go:[0-9]+\\] //; s/ pod=\"ch37\\/[a-z0-9-]+\"//; s/ logger=\"Bind.DefaultBinder\"//'; done"
H 06-serre-v2 "kubectl apply -f ordonnanceur-serre-v2.yaml >/dev/null; $K rollout restart deploy/ordonnanceur-serre >/dev/null; $K rollout status deploy/ordonnanceur-serre --timeout=120s >/dev/null; sleep 5; $K rollout restart deploy/serre >/dev/null; $K rollout status deploy/serre --timeout=120s >/dev/null; sleep 3; $K get pods -l app=serre -o custom-columns=POD:.metadata.name,NOEUD:.spec.nodeName --sort-by=.metadata.name"
H 07-journal-v2 "N=\$($K get pods -l app=ordonnanceur-serre --field-selector status.phase=Running -o name | tail -1); P=\$($K logs \$N | grep -o 'Attempting to schedule pod\" pod=\"ch37/serre-[a-z0-9-]*' | head -1 | sed 's/.*ch37\\///'); echo \"premier Pod traité : \$P\"; $K logs \$N | grep \"pod=\\\"ch37/\$P\\\"\" | grep -E 'Plugin scored|final score|Attempting to bind' | sed -E 's/^I[0-9 :.]+ +1 [a-z_]+\\.go:[0-9]+\\] //; s/ pod=\"ch37\\/[a-z0-9-]+\"//; s/ logger=\"Bind.DefaultBinder\"//'"
H 08-attente "$K apply -f attente.yaml; sleep 5; $K get pods exigeant glouton retenu; $K get events --field-selector reason=FailedScheduling -o custom-columns=POD:.involvedObject.name,MESSAGE:.message --no-headers | sort -u | cut -c1-230"
H 09-files "$K create sa lecteur-metriques >/dev/null; kubectl create clusterrole cours-lecture-metriques --verb=get --non-resource-url=/metrics >/dev/null 2>&1; kubectl create clusterrolebinding cours-lecture-metriques-ch37 --clusterrole=cours-lecture-metriques --serviceaccount=ch37:lecteur-metriques >/dev/null 2>&1; $metriques"
H 10-etiquette "t0=\$(date +%s.%N); kubectl label node deux-noeuds-m02 disque=ssd; $K wait --for=condition=PodScheduled pod/exigeant --timeout=30s; printf 'placé %.2f s après la pose de l étiquette\n' \$(echo \"\$(date +%s.%N)-\$t0\" | bc); $K get events --field-selector involvedObject.name=exigeant -o custom-columns=RAISON:.reason,COMPOSANT:.reportingComponent,MESSAGE:.message --no-headers | cut -c1-160"
H 11-porte "$K get pod retenu -o jsonpath='{.status.conditions[0].reason} : {.status.conditions[0].message}{\"\\n\"}'; $K patch pod retenu --type=json -p '[{\"op\":\"remove\",\"path\":\"/spec/schedulingGates\"}]'; sleep 3; $K get pod retenu -o custom-columns=POD:.metadata.name,STATUT:.status.phase,NOEUD:.spec.nodeName"
H 12-binding "$K apply -f sans-scheduler.yaml; sleep 5; $K get pod orphelin -o custom-columns=POD:.metadata.name,STATUT:.status.phase,NOEUD:.spec.nodeName; $K create --raw /api/v1/namespaces/ch37/pods/orphelin/binding -f binding.json; echo; sleep 3; $K get pod orphelin -o custom-columns=POD:.metadata.name,STATUT:.status.phase,NOEUD:.spec.nodeName; $K get events --field-selector involvedObject.name=orphelin -o custom-columns=RAISON:.reason,COMPOSANT:.reportingComponent --no-headers; $K create --raw /api/v1/namespaces/ch37/pods/orphelin/binding -f binding.json"
H 13-ex-hasard "kubectl proxy --port=8011 >/dev/null & P=\$!; sleep 1; python3 -u ordonnanceur-hasard.py > h.txt 2>&1 & S=\$!; sleep 1; $K apply -f hasard.yaml >/dev/null; sleep 8; kill \$S \$P; cat h.txt"
H 14-ex-direct "kubectl cordon deux-noeuds-m02; $K apply -f direct.yaml; sleep 5; $K get pod direct -o custom-columns=POD:.metadata.name,STATUT:.status.phase,NOEUD:.spec.nodeName; $K get events --field-selector involvedObject.name=direct -o custom-columns=RAISON:.reason,COMPOSANT:.reportingComponent --no-headers; kubectl get node deux-noeuds-m02; kubectl uncordon deux-noeuds-m02; $K delete pod direct --wait=false"
H 15-ex-glouton "$metriques"
