#!/usr/bin/env bash
# Chapitre 15 : pourquoi un orchestrateur. Cluster minikube par défaut, namespace « ch15 » (recréé).
cd "$(dirname "$0")"; O=$PWD/out/ch15; rm -rf $O; mkdir -p $O
export PATH=~/.local/opt/cours-k8s/bin:$PATH
H() { local n=$1; shift; echo "### $n : $*"; timeout 300 bash -c "$*" 2>&1 | grep -v '^W[0-9]' > $O/$n.txt; head -c 9000 $O/$n.txt; }
kubectl delete namespace ch15 --wait=true >/dev/null 2>&1; kubectl create namespace ch15 >/dev/null; kubectl config set-context --current --namespace=ch15 >/dev/null
H 01-creer "kubectl create deployment vitrine --image=nginx:1.30-alpine --replicas=3 && kubectl rollout status deployment/vitrine --timeout=90s && kubectl get deployments,replicasets,pods -o wide"
H 02-chaine "kubectl create deployment sonde --image=nginx:1.30-alpine >/dev/null && kubectl rollout status deployment/sonde --timeout=60s >/dev/null && kubectl get events -o json | jq -r '[.items[] | select(.involvedObject.name|startswith(\"sonde\"))] | sort_by(.metadata.resourceVersion|tonumber) | .[] | [(.eventTime // .firstTimestamp)[11:23], .involvedObject.kind, .reason, (.reportingComponent // .source.component), .message[0:70]] | @tsv' | column -t -s \"\$(printf '\\t')\"; kubectl delete deployment sonde >/dev/null"
H 03-spec-status "kubectl get deployment vitrine -o yaml | sed -n '/^spec:/,/^  template:/p;/^status:/,\$p'"
H 04-supprimer-pod "P=\$(kubectl get pods -o name | head -1); (timeout 8 kubectl get pods --watch --output-watch-events > $O/04-watch.txt 2>&1 &); sleep 1; kubectl delete \$P --wait=false; sleep 8; cat $O/04-watch.txt; kubectl get pods"
H 05-tuer-conteneur "P=\$(kubectl get pods -o jsonpath='{.items[0].metadata.name}'); C=\$(minikube ssh -- sudo crictl ps --name nginx --label io.kubernetes.pod.name=\$P -q | tr -d '\r'); echo pod=\$P conteneur=\$C; minikube ssh -- sudo crictl stop \$C >/dev/null; sleep 6; kubectl get pod \$P; kubectl get events --field-selector involvedObject.name=\$P --sort-by=.lastTimestamp | tail -4"
H 06-echelle "kubectl scale deployment vitrine --replicas=5 && kubectl rollout status deployment/vitrine --timeout=60s && kubectl get pods; kubectl scale deployment vitrine --replicas=2 && sleep 3 && kubectl get pods"
H 07-verbeux "kubectl get pods -v=6 2>&1 | grep -E 'GET|Response' | sed 's/^I[0-9]* [0-9:.]* *[0-9]* [a-z_.]*:[0-9]*\] //' | head -5"
H 08-watch-brut "(timeout 10 kubectl get --raw '/api/v1/namespaces/ch15/pods?watch=1&labelSelector=app=vitrine' > $O/08-brut.json 2>/dev/null &); sleep 1; kubectl delete \$(kubectl get pods -o name | head -1) --wait=false >/dev/null; sleep 9; jq -r '[.type, .object.metadata.name, .object.status.phase, (.object.metadata.deletionTimestamp // \"-\")] | @tsv' $O/08-brut.json"
H 09-plan-controle "minikube ssh -- ls -l /etc/kubernetes/manifests; kubectl get --raw='/readyz?verbose' | tail -4; minikube ssh -- \"sudo grep -E 'leader-elect|controllers=' /etc/kubernetes/manifests/kube-controller-manager.yaml\""
H 10-etcd "kubectl exec -n kube-system etcd-minikube -- etcdctl --endpoints=https://127.0.0.1:2379 --cacert=/var/lib/minikube/certs/etcd/ca.crt --cert=/var/lib/minikube/certs/etcd/server.crt --key=/var/lib/minikube/certs/etcd/server.key get --prefix /registry/ --keys-only | grep '/ch15/' | grep -v events; kubectl exec -n kube-system etcd-minikube -- etcdctl --endpoints=https://127.0.0.1:2379 --cacert=/var/lib/minikube/certs/etcd/ca.crt --cert=/var/lib/minikube/certs/etcd/server.crt --key=/var/lib/minikube/certs/etcd/server.key get --prefix /registry/ --keys-only | grep -c ."
H 11-controleurs "kubectl logs -n kube-system kube-controller-manager-minikube | grep -oE '\"Starting [^\"]*controller[^\"]*\"' | sort -u | wc -l; kubectl logs -n kube-system kube-controller-manager-minikube | grep -oE '\"Starting [^\"]*controller[^\"]*\"' | sort -u | head -12"
