#!/usr/bin/env bash
# Chapitre 32 : l'ordonnancement fin. Profil minikube « deux-noeuds » avec 3 nœuds (m03 ajouté par minikube node add),
# le profil principal arrêté. Namespace ch32 (recréé). Laisse les zones étiquetées et le namespace ch32.
cd "$(dirname "$0")"; O=$PWD/out/ch32; rm -rf $O; mkdir -p $O; cp -a ../kits/ordonnancement $O/m
export PATH=~/.local/opt/cours-k8s/bin:$PATH LC_ALL=C
KK="kubectl --context deux-noeuds"; K="$KK -n ch32"
H() { local n=$1; shift; echo "### $n : $*"; (cd $O/m && timeout 600 bash -c "export KUBECONFIG=\$HOME/.kube/config; $*") 2>&1 | grep -v '^W[0-9]' > $O/$n.txt; head -c 9000 $O/$n.txt; }
ou() { $K get pods -l app=$1 -o custom-columns=POD:.metadata.name,NOEUD:.spec.nodeName,ETAT:.status.phase --no-headers | sort -k2; }
$KK delete namespace ch32 --wait=true >/dev/null 2>&1; $KK delete priorityclass fond critique --ignore-not-found >/dev/null
$KK taint nodes --all dedie- maintenance- >/dev/null 2>&1
$KK create namespace ch32 >/dev/null; kubectl config use-context deux-noeuds >/dev/null; kubectl config set-context --current --namespace=ch32 >/dev/null

H 01-noeuds "./zones.sh; $KK get nodes -L topology.kubernetes.io/zone,disque; $KK get nodes -o custom-columns=NOM:.metadata.name,CPU:.status.allocatable.cpu,MEMOIRE:.status.allocatable.memory"
H 02-selecteur "$K apply -f selecteur.yaml -f introuvable.yaml; sleep 8; $K get pods -o wide | cut -c1-80; $K describe pod introuvable | sed -n '/^Events:/,\$p'; $K delete pod rapide introuvable --wait=false"
H 03-preference "$K apply -f preference.yaml; $K rollout status deploy/preference --timeout=60s >/dev/null; $KK get pods -n ch32 -l app=preference -o custom-columns=POD:.metadata.name,NOEUD:.spec.nodeName --no-headers | sort -k2; $K delete deploy preference"
H 04-dispersion "$K apply -f dispersion.yaml; sleep 12; $K get pods -l app=dispersion -o custom-columns=POD:.metadata.name,NOEUD:.spec.nodeName,ETAT:.status.phase --no-headers | sort -k2; P=\$($K get pods -l app=dispersion --field-selector status.phase=Pending -o name); $K describe \$P | sed -n '/^Events:/,\$p'; $K delete deploy dispersion"
H 05-voisin "$K apply -f voisin.yaml; sleep 8; $K get pods cache voisin -o custom-columns=POD:.metadata.name,NOEUD:.spec.nodeName,ETAT:.status.phase; $K delete pod cache voisin --wait=false"
H 06-repartition "$K apply -f sans-contrainte.yaml -f repartition.yaml; sleep 12; for a in sans-contrainte repartition; do echo \"== \$a\"; $K get pods -l app=\$a -o custom-columns=NOEUD:.spec.nodeName --no-headers | sort | uniq -c; done; $K scale deploy repartition --replicas=9; sleep 6; echo '== repartition, 9 répliques'; $K get pods -l app=repartition -o custom-columns=NOEUD:.spec.nodeName --no-headers | sort | uniq -c; $K delete deploy sans-contrainte repartition"
H 07-taint "$KK taint node deux-noeuds-m03 dedie=calcul:NoSchedule; $KK describe node deux-noeuds-m03 | grep Taints; $K apply -f selecteur.yaml; sed 's/name: rapide/name: sans-tolerance/; s/    disque: ssd/    disque: ssd/' selecteur.yaml | $K apply -f -; $K delete pod rapide --wait=false >/dev/null; $K apply -f dedie.yaml; sleep 8; $K get pods -o custom-columns=POD:.metadata.name,NOEUD:.spec.nodeName,ETAT:.status.phase; $K describe pod sans-tolerance | sed -n '/^Events:/,\$p' | tail -1; $K delete pod sans-tolerance calcul --wait=false >/dev/null"
H 08-noexecute "$K apply -f sans-contrainte.yaml; $K rollout status deploy/sans-contrainte --timeout=60s >/dev/null; echo avant; $K get pods -l app=sans-contrainte -o custom-columns=NOEUD:.spec.nodeName --no-headers | sort | uniq -c; $KK taint node deux-noeuds-m02 maintenance=oui:NoExecute; sleep 10; echo après; $K get pods -l app=sans-contrainte -o custom-columns=NOEUD:.spec.nodeName --no-headers | sort | uniq -c; $K get events --field-selector reason=TaintManagerEviction -o custom-columns=POD:.involvedObject.name,MESSAGE:.message | head -3; $KK -n kube-system get pods -o wide --field-selector spec.nodeName=deux-noeuds-m02 | cut -c1-70; $KK -n kube-system get ds kube-proxy -o jsonpath='{.spec.template.spec.tolerations}{\"\\n\"}'; $KK taint node deux-noeuds-m02 maintenance-; $KK taint node deux-noeuds-m03 dedie-; $K delete deploy sans-contrainte"
H 09-priorites "$KK apply -f priorites.yaml; $KK get priorityclass; $K apply -f remplissage.yaml; sleep 10; $K get pods -l app=remplissage -o custom-columns=POD:.metadata.name,NOEUD:.spec.nodeName,ETAT:.status.phase --no-headers | sort -k2; for n in deux-noeuds deux-noeuds-m02 deux-noeuds-m03; do echo \"\$n : \$($KK describe node \$n | grep -A5 'Allocated resources' | grep cpu | awk '{print \$2, \$3}')\"; done"
H 10-preemption "$K apply -f urgent.yaml; sleep 15; $K get pods -o custom-columns=POD:.metadata.name,NOEUD:.spec.nodeName,ETAT:.status.phase,PRIORITE:.spec.priority --sort-by=.metadata.creationTimestamp; $K get events --sort-by=.metadata.resourceVersion -o custom-columns=RAISON:.reason,OBJET:.involvedObject.name,MESSAGE:.message | grep -E 'Preempted|Scheduled|FailedScheduling' | grep -E 'urgent|Preempted|remplissage' | tail -6 | cut -c1-200"
