#!/usr/bin/env bash
# Chapitre 27, Job et CronJob : cluster minikube principal. Namespace « ch27 » (recréé).
# Remplace le Pod purge de Colis par le CronJob purge. Laisse Colis ainsi (http://192.168.49.100/).
cd "$(dirname "$0")"; O=$PWD/out/ch27; rm -rf $O; mkdir -p $O; cp -a ../kits/taches $O/m
export PATH=~/.local/opt/cours-k8s/bin:$PATH LC_ALL=C
KK="kubectl --context minikube"; K="$KK -n ch27"; KC="$KK -n colis"; IP=192.168.49.100
H() { local n=$1; shift; echo "### $n : $*"; (cd $O/m && timeout 900 bash -c "$*") 2>&1 | grep -v '^W[0-9]' > $O/$n.txt; head -c 9000 $O/$n.txt; }
$KK delete namespace ch27 --wait=true >/dev/null 2>&1; $KK create namespace ch27 >/dev/null
$KC delete cronjob purge --ignore-not-found >/dev/null; $KC delete job --all >/dev/null 2>&1

H 01-compte "$K apply -f compte.yaml; $K wait --for=condition=Complete job/compte --timeout=180s; $K get job compte; $K get pods -l job-name=compte; $K logs job/compte; $K get job compte -o jsonpath='{.spec.completions} {.spec.parallelism} {.spec.backoffLimit} {.spec.completionMode}{\"\\n\"}{.status.conditions[*].type}{\"\\n\"}'"
H 02-echec "d=\$(date +%s); $K apply -f echec.yaml; $K wait --for=condition=Failed job/echec --timeout=300s >/dev/null; echo \"échec après \$(( \$(date +%s)-d )) s\"; $K get job echec; $K get pods -l job-name=echec --sort-by=.metadata.creationTimestamp; for p in \$($K get pods -l job-name=echec --sort-by=.metadata.creationTimestamp -o name); do $K logs \$p; done; $K get job echec -o jsonpath='{.status.conditions[?(@.type==\"Failed\")].reason}: {.status.conditions[?(@.type==\"Failed\")].message}{\"\\n\"}'"
H 03-relance "d=\$(date +%s); $K apply -f relance.yaml; sleep 25; $K get pods -l job-name=relance; $K logs job/relance --previous 2>/dev/null | tail -1; $K wait --for=condition=Failed job/relance --timeout=300s >/dev/null; echo \"échec après \$(( \$(date +%s)-d )) s\"; $K get pods -l job-name=relance; $K get job relance -o jsonpath='{.status.conditions[?(@.type==\"Failed\")].reason}{\"\\n\"}'"
H 04-toujours "sed 's/restartPolicy: Never/restartPolicy: Always/; s/name: echec\$/name: toujours/' echec.yaml | $K apply -f -"
H 05-politique "d=\$(date +%s); $K apply -f politique.yaml; $K wait --for=condition=Failed job/politique --timeout=120s >/dev/null; echo \"échec après \$(( \$(date +%s)-d )) s\"; $K get pods -l job-name=politique; $K logs job/politique; $K get job politique -o jsonpath='{.status.conditions[?(@.type==\"Failed\")].reason}: {.status.conditions[?(@.type==\"Failed\")].message}{\"\\n\"}'"
H 06-delai "$K apply -f delai.yaml; sleep 15; $K get job delai; $K get job delai -o jsonpath='{.status.conditions[?(@.type==\"Failed\")].reason}: {.status.conditions[?(@.type==\"Failed\")].message}{\"\\n\"}'; $K get pods -l job-name=delai; sleep 35; $K get job delai"
H 07-tranches "d=\$(date +%s); $K apply -f tranches.yaml; $K wait --for=condition=Complete job/tranches --timeout=600s >/dev/null; echo \"fini en \$(( \$(date +%s)-d )) s\"; $K get job tranches; $K get pods -l job-name=tranches --sort-by=.status.startTime -o custom-columns='NOM:.metadata.name,INDEX:.metadata.annotations.batch\\.kubernetes\\.io/job-completion-index,DÉBUT:.status.startTime,FIN:.status.containerStatuses[0].state.terminated.finishedAt'; for p in \$($K get pods -l job-name=tranches -o name); do $K logs \$p; done | sort -t' ' -k2 -n"
H 08-sequentiel "$K delete job tranches >/dev/null; for par in 1 8; do sed \"s/parallelism: 4/parallelism: \$par/; s/name: tranches\$/name: tranches-\$par/\" tranches.yaml | $K apply -f - >/dev/null; d=\$(date +%s); $K wait --for=condition=Complete job/tranches-\$par --timeout=900s >/dev/null; echo \"parallelism \$par : \$(( \$(date +%s)-d )) s\"; $K delete job tranches-\$par >/dev/null; done; $KK get node minikube -o jsonpath='{.status.allocatable.cpu} CPU allouables{\"\\n\"}'; nproc; minikube ssh -- nproc"
H 09-cron "date -u +%T; $K apply -f horloge.yaml -f long.yaml; sleep 215; date -u +%T; $K get cronjobs; $K get jobs -l '!batch.kubernetes.io/job-name' 2>/dev/null; $K get jobs; for j in \$($K get jobs -o name | grep horloge); do $K logs \$j; done; $K get events --field-selector involvedObject.kind=CronJob --sort-by=.metadata.resourceVersion -o custom-columns=OBJET:.involvedObject.name,RAISON:.reason,MESSAGE:.message; $K delete cronjob horloge long"
H 10-validation "sed 's/name: horloge\$/name: mauvaise/; s|\"\\* \\* \\* \\* \\*\"|\"61 * * * *\"|' horloge.yaml | $K apply -f -; sed 's/name: horloge\$/name: mauvaise/; s/Europe\\/Paris/Europe\\/Pariss/' horloge.yaml | $K apply -f -; sed 's/name: horloge\$/name: mauvaise/; s|\"\\* \\* \\* \\* \\*\"|\"CRON_TZ=UTC * * * * *\"|' horloge.yaml | $K apply -f -; sed 's/name: horloge\$/name: mauvaise/; s|\"\\* \\* \\* \\* \\*\"|\"*/61 * * * *\"|' horloge.yaml | $K apply -f -; $K delete cronjob mauvaise"
# Colis
H 11-colis-cron "$KC delete pod purge --ignore-not-found; $KK apply -f colis/50-purge.yaml; $KC get cronjob purge"
H 12-colis-purge "for n in 'Hedy Lamarr' 'Joan Clarke'; do curl -s -X POST http://$IP/api/colis -H 'Content-Type: application/json' -d \"{\\\"destinataire\\\":\\\"\$n\\\",\\\"depart\\\":\\\"Lyon\\\",\\\"arrivee\\\":\\\"Brest\\\",\\\"poids_kg\\\":0.8}\" | jq -c '{id, destinataire}'; done; sleep 5; for i in \$(curl -s http://$IP/api/colis | jq -r '.[] | select(.destinataire==\"Hedy Lamarr\" or .destinataire==\"Joan Clarke\") | .id'); do curl -s -X POST http://$IP/api/colis/\$i/livraison | jq -c '{id, statut}'; done; $KC exec postgres-0 -- psql -U colis -d colis -c \"UPDATE colis SET livre_le = now() - interval '40 days' WHERE destinataire = 'Hedy Lamarr';\"; $KC exec postgres-0 -- psql -U colis -d colis -c 'SELECT id, destinataire, statut, livre_le::date FROM colis ORDER BY id;'; $KC create job purge-manuelle --from=cronjob/purge; $KC wait --for=condition=Complete job/purge-manuelle --timeout=120s; $KC logs job/purge-manuelle; $KC exec postgres-0 -- psql -U colis -d colis -c 'SELECT id, destinataire, statut FROM colis ORDER BY id;'; $KC get job purge-manuelle -o jsonpath='{.metadata.annotations}{\"\\n\"}'"
