#!/usr/bin/env bash
# Chapitre 22 : la santé des Pods. Namespace « ch22 » (recréé), manifestes de kits/sante.
cd "$(dirname "$0")"; O=$PWD/out/ch22; rm -rf $O; mkdir -p $O; cp -a ../kits/sante $O/m
export PATH=~/.local/opt/cours-k8s/bin:$PATH LC_ALL=C
kubectl config use-context minikube >/dev/null
kubectl delete namespace ch22 --wait=true >/dev/null 2>&1; kubectl create namespace ch22 >/dev/null; kubectl config set-context --current --namespace=ch22 >/dev/null
H() { local n=$1; shift; echo "### $n : $*"; (cd $O/m && timeout 500 bash -c "$*") 2>&1 | grep -v '^W[0-9]' > $O/$n.txt; head -c 9000 $O/$n.txt; }
H 01-liveness "kubectl apply -f liveness.yaml; t0=\$(date +%s); last=''; while [ \$((\$(date +%s)-t0)) -lt 75 ]; do s=\$(kubectl get pod malade --no-headers | awk '{print \$2, \$3, \$4}'); [ \"\$s\" != \"\$last\" ] && echo \"t=\$((\$(date +%s)-t0)) s : \$s\" && last=\$s; sleep 1; done; kubectl get events --field-selector involvedObject.name=malade --sort-by=.lastTimestamp -o custom-columns=RAISON:.reason,NB:.count,MESSAGE:.message | cut -c1-160"
H 02-readiness "kubectl apply -f readiness.yaml; kubectl rollout status deployment/pret --timeout=90s; kubectl run client --image=busybox:1.37 --restart=Never -- sleep 3600 >/dev/null; kubectl wait --for=condition=Ready pod/client --timeout=60s >/dev/null; kubectl get pods -l app=pret; kubectl exec client -- sh -c 'for i in \$(seq 1 20); do wget -q -O - http://pret/hostname; echo; done' | sort | uniq -c"
H 03-pas-pret "P=\$(kubectl get pods -l app=pret -o jsonpath='{.items[0].metadata.name}'); echo \"on retire /tmp/pret de \$P\"; kubectl exec \$P -- rm /tmp/pret; sleep 5; kubectl get pods -l app=pret; kubectl get endpointslices -l kubernetes.io/service-name=pret -o json | jq -r '.items[0].endpoints[] | \"\(.targetRef.name) ready=\(.conditions.ready)\"'; kubectl exec client -- sh -c 'for i in \$(seq 1 20); do wget -q -O - http://pret/hostname; echo; done' | sort | uniq -c; kubectl get events --field-selector involvedObject.name=\$P,reason=Unhealthy -o custom-columns=MESSAGE:.message | tail -1; kubectl exec \$P -- touch /tmp/pret; sleep 4; kubectl get pods -l app=pret"
H 04-sans-startup "kubectl apply -f lent-sans-startup.yaml; t0=\$(date +%s); last=''; while [ \$((\$(date +%s)-t0)) -lt 130 ]; do s=\$(kubectl get pod lent-sans-startup --no-headers | awk '{print \$2, \$3, \$4}'); [ \"\$s\" != \"\$last\" ] && echo \"t=\$((\$(date +%s)-t0)) s : \$s\" && last=\$s; sleep 1; done; kubectl logs lent-sans-startup --previous; kubectl get pod lent-sans-startup -o jsonpath='{.status.containerStatuses[0].lastState.terminated.exitCode} {.status.containerStatuses[0].lastState.terminated.startedAt} {.status.containerStatuses[0].lastState.terminated.finishedAt}{\"\n\"}'; kubectl get events --field-selector involvedObject.name=lent-sans-startup -o custom-columns=PREMIER:.firstTimestamp,NB:.count,RAISON:.reason,MESSAGE:.message | grep -E 'Unhealthy|Killing|Started' | cut -c1-150"
H 05-avec-startup "kubectl apply -f lent-avec-startup.yaml; t0=\$(date +%s); last=''; while [ \$((\$(date +%s)-t0)) -lt 50 ]; do s=\$(kubectl get pod lent-avec-startup --no-headers | awk '{print \$2, \$3, \$4}'); st=\$(kubectl get pod lent-avec-startup -o jsonpath='{.status.containerStatuses[0].started}'); [ \"\$s \$st\" != \"\$last\" ] && echo \"t=\$((\$(date +%s)-t0)) s : \$s started=\$st\" && last=\"\$s \$st\"; sleep 1; done; kubectl logs lent-avec-startup"
H 06-arret-propre "kubectl apply -f arret-propre.yaml; kubectl wait --for=condition=Ready pod/arret-propre --timeout=60s >/dev/null; sleep 2; d=\$(date +%s%N); echo \"\$(date -u +%T) kubectl delete\"; kubectl delete pod arret-propre --wait=false >/dev/null; (kubectl logs -f arret-propre 2>/dev/null &); kubectl wait --for=delete pod/arret-propre --timeout=60s >/dev/null; echo \"supprimé en \$(( (\$(date +%s%N)-d)/1000000 )) ms\""
H 07-arret-sourd "kubectl apply -f arret-sourd.yaml; kubectl wait --for=condition=Ready pod/arret-sourd --timeout=60s >/dev/null; sleep 2; d=\$(date +%s%N); echo \"\$(date -u +%T) kubectl delete\"; kubectl delete pod arret-sourd --wait=false >/dev/null; sleep 2; kubectl get pod arret-sourd; kubectl wait --for=delete pod/arret-sourd --timeout=60s >/dev/null; echo \"supprimé en \$(( (\$(date +%s%N)-d)/1000000 )) ms\"; kubectl get events --field-selector involvedObject.name=arret-sourd -o custom-columns=RAISON:.reason,MESSAGE:.message | tail -2"
H 08-prestop "kubectl apply -f prestop.yaml; kubectl wait --for=condition=Ready pod/prestop --timeout=60s >/dev/null; sleep 2; echo \"\$(date -u +%T) kubectl delete\"; kubectl delete pod prestop --wait=false >/dev/null; (kubectl logs -f prestop 2>/dev/null &); kubectl wait --for=delete pod/prestop --timeout=60s >/dev/null; echo \"\$(date -u +%T) Pod supprimé\""
H 09-sondes-defaut "kubectl get deployment pret -o jsonpath='{.spec.template.spec.containers[0].readinessProbe}' | jq ."
