#!/usr/bin/env bash
# Chapitre 33 : la disponibilité. Profil « deux-noeuds » à 3 nœuds, zones et étiquette disque=ssd posées par
# kits/ordonnancement/zones.sh. Namespace ch33 (recréé). Retire l'image agnhost des nœuds 1 et 2 pour montrer
# le coût d'un tirage pendant un drain. Laisse tous les nœuds planifiables.
cd "$(dirname "$0")"; O=$PWD/out/ch33; rm -rf $O; mkdir -p $O; cp -a ../kits/disponibilite $O/m
export PATH=~/.local/opt/cours-k8s/bin:$PATH LC_ALL=C
KK="kubectl --context deux-noeuds"; K="$KK -n ch33"; IMG=registry.k8s.io/e2e-test-images/agnhost:2.61
H() { local n=$1; shift; echo "### $n : $*"; (cd $O/m && timeout 600 bash -c "$*") 2>&1 | grep -v '^W[0-9]' > $O/$n.txt; head -c 9000 $O/$n.txt; }
$KK delete namespace ch33 --wait=true >/dev/null 2>&1; $KK uncordon deux-noeuds deux-noeuds-m02 deux-noeuds-m03 >/dev/null 2>&1
(cd ../kits/ordonnancement && KUBECONFIG=$HOME/.kube/config kubectl config use-context deux-noeuds >/dev/null && ./zones.sh >/dev/null)
for n in deux-noeuds deux-noeuds-m02; do minikube ssh -p deux-noeuds -n $n -- sudo crictl rmi $IMG >/dev/null 2>&1; done
$KK create namespace ch33 >/dev/null
journal() { $K logs client --since-time=$1 | grep -v '^wget'; }

H 01-deploiement "$K apply -f vitrine.yaml -f client.yaml; $K rollout status deploy/vitrine --timeout=180s >/dev/null; $K wait --for=condition=Ready pod/client --timeout=120s >/dev/null; $K get pods -o custom-columns=POD:.metadata.name,NOEUD:.spec.nodeName,PRET:.status.containerStatuses[0].ready; sleep 3; $K logs client --tail=2"
H 02-sans-pdb "t=\$(date -u +%Y-%m-%dT%H:%M:%SZ); d=\$(date +%s); $KK drain deux-noeuds-m03 --ignore-daemonsets --delete-emptydir-data 2>&1 | grep -v '^Warning'; echo \"drain terminé en \$(( \$(date +%s)-d )) s\"; $K rollout status deploy/vitrine --timeout=180s >/dev/null; sleep 5; $K logs client --since-time=\$t | grep -v '^wget' | grep -v 'echecs=0' ; echo \"secondes sans échec : \$($K logs client --since-time=\$t | grep -c 'echecs=0')\"; $K get pods -l app=vitrine -o custom-columns=POD:.metadata.name,NOEUD:.spec.nodeName --no-headers; $K get events --field-selector reason=Pulled --sort-by=.lastTimestamp | grep vitrine | tail -2 | cut -c1-190"
H 03-pdb "$KK uncordon deux-noeuds-m03; $K rollout restart deploy/vitrine; $K rollout status deploy/vitrine --timeout=120s >/dev/null; sleep 8; $K get pods -l app=vitrine -o custom-columns=POD:.metadata.name,NOEUD:.spec.nodeName --no-headers; $K apply -f pdb.yaml; sleep 3; $K get pdb vitrine"
H 04-avec-pdb "t=\$(date -u +%Y-%m-%dT%H:%M:%SZ); d=\$(date +%s); $KK drain deux-noeuds-m03 --ignore-daemonsets --delete-emptydir-data 2>&1 | grep -v '^Warning'; echo \"drain terminé en \$(( \$(date +%s)-d )) s\"; sleep 5; echo \"lignes avec échecs : \$($K logs client --since-time=\$t | grep -v '^wget' | grep -vc 'echecs=0')\"; echo \"secondes sans échec : \$($K logs client --since-time=\$t | grep -c 'echecs=0')\"; $K get pods -l app=vitrine -o custom-columns=POD:.metadata.name,NOEUD:.spec.nodeName --no-headers; $K get pdb vitrine"
H 05-solo "$KK uncordon deux-noeuds-m03; $K apply -f solo.yaml; $K rollout status deploy/solo --timeout=60s >/dev/null; $K get pdb solo; d=\$(date +%s); timeout 30 $KK drain deux-noeuds-m03 --ignore-daemonsets --delete-emptydir-data 2>&1 | grep -v '^Warning' | grep -E 'cordoned|solo' | head -4; echo \"... interrompu après \$(( \$(date +%s)-d )) s\"; $KK get node deux-noeuds-m03; $KK drain deux-noeuds-m03 --ignore-daemonsets --timeout=15s 2>&1 | grep -E 'global timeout'"
H 06-supprimer "P=\$($K get pods -l app=solo -o name); $K delete \$P; sleep 3; $K get pods -l app=solo; $K describe pods -l app=solo | grep FailedScheduling | cut -c1-170; $KK uncordon deux-noeuds-m03; $K wait --for=condition=Ready pod -l app=solo --timeout=60s >/dev/null; $K get pods -l app=solo; $K delete -f solo.yaml"
H 07-malades "$K patch deploy vitrine --type json -p '[{\"op\":\"replace\",\"path\":\"/spec/strategy\",\"value\":{\"type\":\"Recreate\"}},{\"op\":\"replace\",\"path\":\"/spec/template/spec/containers/0/readinessProbe/httpGet\",\"value\":{\"path\":\"/hostname\",\"port\":9999}}]'; sleep 25; $K get pods -l app=vitrine -o custom-columns=POD:.metadata.name,NOEUD:.spec.nodeName,PRET:.status.containerStatuses[0].ready --no-headers; $K get pdb vitrine; d=\$(date +%s); timeout 30 $KK drain deux-noeuds-m03 --ignore-daemonsets 2>&1 | grep -E 'violate' | head -1; echo \"... interrompu après \$(( \$(date +%s)-d )) s\"; $K patch pdb vitrine --type merge -p '{\"spec\":{\"unhealthyPodEvictionPolicy\":\"AlwaysAllow\"}}'; d=\$(date +%s); $KK drain deux-noeuds-m03 --ignore-daemonsets --timeout=60s 2>&1 | grep -E 'evicted|drained'; echo \"drain terminé en \$(( \$(date +%s)-d )) s\"; $KK uncordon deux-noeuds-m03"
H 08-maj "$K delete pdb vitrine; $K delete deploy vitrine --wait=true >/dev/null; $K apply -f vitrine.yaml >/dev/null; $K rollout status deploy/vitrine --timeout=120s >/dev/null; sed 's/minAvailable: 2/minAvailable: 3/' pdb.yaml | $K apply -f -; sleep 3; $K get pdb vitrine; d=\$(date +%s); $K rollout restart deploy/vitrine; $K rollout status deploy/vitrine --timeout=120s | tail -1; echo \"mise à jour terminée en \$(( \$(date +%s)-d )) s\"; $K delete pdb vitrine"
