#!/usr/bin/env bash
# Chapitre 14 : chaîne d'approvisionnement. Recrée SES objets par leur nom : conteneur et volume « registre »,
# constructeur buildx « cours », images fuite:1.0 (supprimée). Laisse le registre et le constructeur en place.
cd "$(dirname "$0")"; O=$PWD/out/ch14r; rm -rf $O; mkdir -p $O/cle
export PATH=~/.local/opt/cours-k8s/bin:$PATH DOCKER_CONFIG=~/.local/opt/cours-k8s/docker-config TRIVY_CACHE_DIR=~/.local/opt/cours-k8s/cache/trivy
export COSIGN_PASSWORD=mot-de-passe-du-cours
K=$PWD/../kits/tampon; R=localhost:5001/cours/tampon
H() { local n=$1; shift; echo "### $n : $*"; (cd $O && timeout 900 bash -c "$*") 2>&1 | grep -v 'docker-desktop://' > $O/$n.txt; head -c 9000 $O/$n.txt; }
docker rm -f registre >/dev/null 2>&1; docker volume rm registre >/dev/null 2>&1; docker buildx rm cours >/dev/null 2>&1
H 01-registre "docker run -d --name registre -p 5001:5000 -v registre:/var/lib/registry -e REGISTRY_STORAGE_DELETE_ENABLED=true registry:3 >/dev/null; sleep 2; curl -s localhost:5001/v2/_catalog"
H 02-builder "docker buildx create --name cours --driver docker-container --driver-opt network=host --bootstrap >/dev/null 2>&1; docker buildx ls | grep -A1 '^cours'"
H 03-push "cd $K && docker buildx build --builder cours --platform linux/amd64,linux/arm64 --build-arg VERSION=1.0.0 --sbom=true --provenance=mode=max -t $R:1.0.0 --push . 2>&1 | grep -E 'pushing manifest|naming to|exporting (attestation|manifest list)' | sed 's/ [0-9.]*s done//' | sort -u"
H 04-inspect "docker buildx imagetools inspect $R:1.0.0"
H 05-sbom "docker buildx imagetools inspect $R:1.0.0 --format '{{json .SBOM}}' > sbom.json; jq -r '.\"linux/amd64\".SPDX | .spdxVersion, (.packages | length), (.packages[] | \"\(.name) \(.versionInfo)\")' sbom.json"
H 06-provenance "docker buildx imagetools inspect $R:1.0.0 --format '{{json .Provenance}}' > prov.json; jq '.\"linux/amd64\".SLSA | {buildType: .buildDefinition.buildType, args: .buildDefinition.externalParameters.request.args, dependances: [.buildDefinition.resolvedDependencies[] | {uri, sha256: .digest.sha256[0:16]}], debut: .runDetails.metadata.startedOn}' prov.json"
H 07-trivy-tampon "trivy image --quiet $R:1.0.0"
H 08-trivy-colis "trivy image --quiet --format json -o colis.json colis:1.0; jq -r '.Results[] | \"\(.Target) [\(.Type)] : \([.Vulnerabilities[]?.Severity] | group_by(.) | map(\"\(.[0])=\(length)\") | join(\" \"))\"' colis.json; echo; jq -r '[.Results[].Vulnerabilities[]? | .Status] | group_by(.) | map(\"\(.[0])=\(length)\") | join(\" \")' colis.json"
H 09-trivy-colis-fix "trivy image --quiet --ignore-unfixed --severity HIGH,CRITICAL colis:1.0"
H 10-exitcode "trivy image --quiet --ignore-unfixed --severity CRITICAL --exit-code 1 colis:1.0 >/dev/null; echo \"CRITICAL corrigeables : code \$?\"; trivy image --quiet --ignore-unfixed --severity HIGH,CRITICAL --exit-code 1 colis:1.0 >/dev/null; echo \"HIGH ou CRITICAL corrigeables : code \$?\""
H 11-pip "docker run --rm colis:1.0 sh -c 'grep -iE \"^(msgpack|setuptools)\" /usr/local/lib/python3.14/site-packages/pip/_vendor/vendor.txt; ls /usr/local/lib/python3.14/site-packages/pip/_vendor/bom.cdx.json'"
H 12-autres "for i in nginx:1.30-alpine python:3.14-slim python:3.14 tampon:naif; do trivy image --quiet --format json -o x.json \$i; echo \"\$i : \$(jq -r '[.Results[]?.Vulnerabilities[]?.Severity] | group_by(.) | map(\"\(.[0])=\(length)\") | join(\" \")' x.json)\"; done; rm x.json"
H 13-sbom-trivy "trivy image --quiet --format cyclonedx -o colis.cdx.json colis:1.0; jq -r '.bomFormat, .specVersion, (.components | length)' colis.cdx.json; jq -r '[.components[] | .purl // \"\" | split(\"/\")[0]] | group_by(.) | map(\"\(.[0])=\(length)\") | join(\" \")' colis.cdx.json; d=\$(date +%s%N); trivy sbom --quiet --format json -o s.json colis.cdx.json; echo \"trivy sbom : \$(( (\$(date +%s%N)-d)/1000000 )) ms, \$(jq '[.Results[]?.Vulnerabilities[]?] | length' s.json) vulnérabilités\""
H 14-config "cd $K && trivy config --quiet Dockerfile.naif 2>&1 | grep -E '^(Tests|Failures|DS-)'; echo ---; trivy config --quiet Dockerfile 2>&1 | grep -E '^(Tests|Failures|DS-)'"
H 15-secret "mkdir -p fuite && cd fuite && printf 'GITHUB_TOKEN=ghp_%s\n' \"\$(head -c 400 /dev/urandom | tr -dc 'A-Za-z0-9' | head -c 36)\" > deploiement.env && printf 'FROM alpine:3.24\nCOPY deploiement.env /tmp/deploiement.env\nRUN rm /tmp/deploiement.env\n' > Dockerfile && docker build -q -t fuite:1.0 . >/dev/null && docker run --rm fuite:1.0 ls -A /tmp; trivy image --quiet --scanners secret fuite:1.0 2>&1 | grep -vE '^\s*\$' | sed -n '/deploiement.env (secrets)/,\$p'; docker rmi fuite:1.0 >/dev/null"
H 16-cles "cd cle && cosign generate-key-pair 2>&1; cosign signing-config create --out sans-journal.json; cat sans-journal.json; echo; ls -l"
H 17-signe "cd cle && D=\$(docker buildx imagetools inspect $R:1.0.0 --format '{{json .Manifest}}' | jq -r .digest); echo \"empreinte : \$D\"; cosign sign --yes --key cosign.key --signing-config sans-journal.json --allow-http-registry $R@\$D 2>&1"
H 18-verifie "cd cle && cosign verify --key cosign.pub --insecure-ignore-tlog=true --allow-http-registry $R:1.0.0 2>&1 | cut -c1-300; echo code=\$?"
H 19-arbre "cosign tree --allow-http-registry $R:1.0.0 2>&1; curl -s localhost:5001/v2/cours/tampon/tags/list"
H 20-pirate "cd $K && docker buildx build --builder cours --platform linux/amd64,linux/arm64 --build-arg VERSION=1.0.0-pirate -t $R:1.0.0 --push . >/dev/null 2>&1; docker buildx imagetools inspect $R:1.0.0 --format '{{json .Manifest}}' | jq -r .digest; cd $O/cle && cosign verify --key cosign.pub --insecure-ignore-tlog=true --allow-http-registry $R:1.0.0 2>&1 | tail -2; echo code=\$?"
H 21-mauvaise-cle "cd cle && mkdir -p autre && cd autre && cosign generate-key-pair >/dev/null 2>&1; D=\$(jq -r '.\"linux/amd64\".SLSA.subject // empty' ../../prov.json >/dev/null; cat ../../17-signe.txt | grep -o 'sha256:[0-9a-f]*' | head -1); cosign verify --key cosign.pub --insecure-ignore-tlog=true --allow-http-registry $R@\$D 2>&1 | tail -1; echo code=\$?; cd .. && cosign verify --key cosign.pub --insecure-ignore-tlog=true --allow-http-registry $R@\$D 2>&1 | grep -c 'signatures were verified'"
H 22-codes "cd cle && O=\$(grep -o 'sha256:[0-9a-f]*' ../17-signe.txt | head -1); cosign verify --key cosign.pub --insecure-ignore-tlog=true --allow-http-registry $R:1.0.0 >/dev/null 2>&1; echo \"étiquette 1.0.0 : code \$?\"; cosign verify --key cosign.pub --insecure-ignore-tlog=true --allow-http-registry $R@\$O >/dev/null 2>&1; echo \"empreinte d'origine : code \$?\"; cosign verify --key autre/cosign.pub --insecure-ignore-tlog=true --allow-http-registry $R@\$O >/dev/null 2>&1; echo \"autre clé : code \$?\""
H 23-menage "P=\$(head -1 20-pirate.txt); O=\$(grep -o 'sha256:[0-9a-f]*' 17-signe.txt | head -1); docker exec registre du -sh /var/lib/registry; curl -s -o /dev/null -w 'DELETE : %{http_code}\n' -X DELETE localhost:5001/v2/cours/tampon/manifests/\$P; docker buildx imagetools create -t $R:1.0.0 $R@\$O >/dev/null 2>&1; curl -s localhost:5001/v2/cours/tampon/tags/list; echo; docker exec registre registry garbage-collect --delete-untagged /etc/distribution/config.yml 2>&1 | grep -E 'marked'; docker exec registre du -sh /var/lib/registry; cd cle && cosign verify --key cosign.pub --insecure-ignore-tlog=true --allow-http-registry $R:1.0.0 >/dev/null 2>&1; echo \"vérification après ménage : code \$?\""
