#!/usr/bin/env bash
# Chapitre 13 : images de production. Images tampon:*, conteneur t13 (supprimé), builder buildx « cours » (laissé en place).
cd "$(dirname "$0")"; O=$PWD/out/ch13r; rm -rf $O; mkdir -p $O
export DOCKER_CONFIG=~/.local/opt/cours-k8s/docker-config
K=$PWD/../kits/tampon; W=$O/tampon; rm -rf $W; cp -a $K $W
H() { local n=$1; shift; echo "### $n : $*"; (cd $W && timeout 600 bash -c "$*") 2>&1 | grep -v 'docker-desktop://' > $O/$n.txt; head -c 8000 $O/$n.txt; }
docker rm -f t13 >/dev/null 2>&1
H 01-naif "docker build -q -f Dockerfile.naif -t tampon:naif . >/dev/null; docker image ls tampon:naif --format '{{.Size}}'; docker history tampon:naif --format '{{.Size}}\t{{.CreatedBy}}' | head -4 | cut -c1-90"
H 02-alpine "docker build -q -f Dockerfile.alpine -t tampon:alpine . >/dev/null; docker run --rm tampon:alpine; echo code=\$?; docker run --rm --entrypoint sh tampon:alpine -c 'ldd /usr/local/bin/tampon'"
H 03-scratch "docker build -q -f Dockerfile.scratch -t tampon:scratch . >/dev/null; docker run -d --rm --name t13 -p 8081:8080 tampon:scratch >/dev/null; sleep 1; curl -s localhost:8081/; curl -s localhost:8081/distant; docker rm -f t13 >/dev/null; docker run --rm --entrypoint sh tampon:scratch 2>&1 | tail -1"
H 04-scratch2 "docker build -q -f Dockerfile.scratch2 -t tampon:scratch2 . >/dev/null; docker run -d --rm --name t13 -p 8081:8080 tampon:scratch2 >/dev/null; sleep 1; curl -s localhost:8081/; curl -s localhost:8081/distant; docker rm -f t13 >/dev/null"
H 05-final "docker build -q --build-arg VERSION=1.0.0 -t tampon:1.0.0 . >/dev/null; docker run -d --rm --name t13 -p 8081:8080 tampon:1.0.0 >/dev/null; sleep 1; curl -s localhost:8081/; curl -s localhost:8081/distant; docker image inspect tampon:1.0.0 --format 'User={{.Config.User}}'; docker rm -f t13 >/dev/null"
H 06-tailles "docker image ls tampon --format '{{.Tag}}\t{{.Size}}'"
H 07-history "docker history tampon:1.0.0 --format '{{.Size}}\t{{.CreatedBy}}' | cut -c1-80"
H 08-debug "docker run -d --rm --name t13 tampon:1.0.0 >/dev/null; sleep 1; docker exec t13 sh 2>&1 | tail -1; docker run --rm --pid container:t13 busybox:1.37 sh -c 'ps; ls /proc/1/root/'; echo ---; docker run --rm --pid container:t13 --cap-add SYS_PTRACE busybox:1.37 sh -c 'ls /proc/1/root/; cat /proc/1/root/etc/passwd'; docker rm -f t13 >/dev/null"
H 09-bases "docker image ls --format '{{.Repository}}:{{.Tag}}\t{{.Size}}' | grep -E '^(python:3.14|gcr.io/distroless/(python3|static|base)-debian13:latest|debian:13-slim|alpine:3.24|golang:1.27)' | sort"
H 10-builder "docker buildx ls | grep -A1 '^cours'"
H 11-multi "docker buildx build --builder cours --platform linux/amd64,linux/arm64 --build-arg VERSION=1.0.0 --output type=oci,dest=$O/tampon-multi.tar . 2>&1 | grep -E '^#[0-9]+ \\[' | sort -u | head -20; mkdir -p $O/oci && tar -xf $O/tampon-multi.tar -C $O/oci && jq . $O/oci/index.json && IDX=\$(jq -r '.manifests[0].digest' $O/oci/index.json | cut -d: -f2) && jq -c '.manifests[] | {platform, type: .annotations[\"vnd.docker.reference.type\"]}' $O/oci/blobs/sha256/\$IDX"
H 12-binaires "IDX=\$(jq -r '.manifests[0].digest' $O/oci/index.json | cut -d: -f2); for a in amd64 arm64; do M=\$(jq -r \".manifests[] | select(.platform.architecture==\\\"\$a\\\") | .digest\" $O/oci/blobs/sha256/\$IDX | cut -d: -f2); L=\$(jq -r '.layers[-1].digest' $O/oci/blobs/sha256/\$M | cut -d: -f2); echo \"\$a : \$(tar -xzOf $O/oci/blobs/sha256/\$L tampon | file - | cut -d, -f1,2)\"; done"
H 13-repro "b() { docker buildx build --builder cours --platform linux/amd64 --no-cache \$2 --build-arg VERSION=1.0.0 --output \"type=oci,dest=$O/r\$1.tar\$3\" . >/dev/null 2>&1; mkdir -p $O/r\$1 && tar -xf $O/r\$1.tar -C $O/r\$1 && echo \"construction \$1 : \$(jq -r '.manifests[0].digest' $O/r\$1/index.json)\"; }; b 1 '' ''; b 2 '' ''; export SOURCE_DATE_EPOCH=1788220800; b 3 --provenance=false ,rewrite-timestamp=true; b 4 --provenance=false ,rewrite-timestamp=true"
H 14-check "printf 'FROM golang:1.27 as construction\nWORKDIR /src\nCOPY . .\nRUN go build -o /tampon .\nCMD /tampon\n' > Dockerfile.lint; docker build --check -f Dockerfile.lint . 2>&1 | grep -E '^(WARNING|Check)'"
H 15-pourquoi "for r in r1 r2 r3; do M=\$(jq -r '.manifests[0].digest' $O/\$r/index.json | cut -d: -f2); C=\$(jq -r .config.digest $O/\$r/blobs/sha256/\$M | cut -d: -f2); L=\$(jq -r '.layers[-1].digest' $O/\$r/blobs/sha256/\$M | cut -d: -f2); echo \"\$r : created \$(jq -r .created $O/\$r/blobs/sha256/\$C), binaire \$(tar -xzOf $O/\$r/blobs/sha256/\$L tampon | sha256sum | cut -c1-12), date du fichier \$(tar -tvzf $O/\$r/blobs/sha256/\$L | awk '{print \$4, \$5}'), couche \${L:0:12}\"; done"
H 16-emulation "I=\$(date +%s); sed 's|^FROM --platform=\\\$BUILDPLATFORM golang|FROM golang|; s|--mount=type=cache,target|--mount=type=cache,id=emule-'\$I',target|' Dockerfile > Dockerfile.emule; sed 's|--mount=type=cache,target|--mount=type=cache,id=croise-'\$I',target|' Dockerfile > Dockerfile.croise; grep -n '^FROM' Dockerfile.emule | head -1; for f in Dockerfile.emule Dockerfile.croise; do docker buildx build --builder cours --platform linux/arm64 --no-cache -f \$f --output type=oci,dest=$O/x.tar . > $O/x.log 2>&1; echo \"\$f : \$(grep -m1 -E 'go build' $O/x.log | grep -o '\\[linux[^]]*\\]' | head -1) \$(grep -A40 'go build' $O/x.log | grep -m1 -E '^#[0-9]+ DONE')\"; done; rm -f $O/x.tar"
H 17-cache "I=\$(date +%s); sed 's|^RUN --mount=type=cache,target=/root/.cache/go-build \\\\\$|RUN \\\\|' Dockerfile > Dockerfile.sanscache; sed 's|--mount=type=cache,target|--mount=type=cache,id=mesure-'\$I',target|' Dockerfile > Dockerfile.aveccache; grep -c mount Dockerfile.sanscache; t() { local d=\$(date +%s%N); docker build -q -f \$1 -t tampon:mesure . >/dev/null; echo \"\$2 : \$(( (\$(date +%s%N)-d)/1000000 )) ms\"; }; echo \"// essai \$I\" >> main.go; t Dockerfile.sanscache 'sans cache de compilation, 1re construction'; echo \"// modif \$(date +%s%N)\" >> main.go; t Dockerfile.sanscache 'sans cache de compilation, après une modification'; t Dockerfile.aveccache 'avec cache de compilation, 1re construction'; echo \"// modif \$(date +%s%N)\" >> main.go; t Dockerfile.aveccache 'avec cache de compilation, après une modification'; docker rmi tampon:mesure >/dev/null"
