#!/usr/bin/env bash
# Chapitre 30 : Kustomize. Recrée le namespace colis-dev (overlay dev de Colis) ; rend l'overlay prod et le vérifie
# à blanc (dry-run côté serveur) sans le déployer, pour rester sous 4 Gio. Suppose la passerelle du chapitre 28.
cd "$(dirname "$0")"; O=$PWD/out/ch30; rm -rf $O; mkdir -p $O; cp -a ../kits/kustomize $O/m
export PATH=~/.local/opt/cours-k8s/bin:$PATH LC_ALL=C
KK="kubectl --context minikube"; KD="$KK -n colis-dev"; IP=192.168.49.102
H() { local n=$1; shift; echo "### $n : $*"; (cd $O/m && timeout 900 bash -c "$*") 2>&1 | grep -v '^W[0-9]' > $O/$n.txt; head -c 9000 $O/$n.txt; }
$KK delete namespace colis-dev colis-prod ch30 --ignore-not-found --wait=true >/dev/null 2>&1
for e in dev prod; do [ -f ../kits/kustomize/colis/overlays/$e/secret.env ] && cp ../kits/kustomize/colis/overlays/$e/secret.env $O/m/colis/overlays/$e/ || printf 'POSTGRES_PASSWORD=%s\n' "$(head -c 18 /dev/urandom | base64 | tr -d '/+=')" > $O/m/colis/overlays/$e/secret.env; done

H 01-version "kubectl version --client"
H 02-base "cd colis && kubectl kustomize base | grep -E '^kind:|^  name:' | paste - -; kubectl kustomize base | grep -B2 -A6 '^kind: ConfigMap'"
H 03-dev "cd colis && kubectl kustomize overlays/dev | grep -E '^kind:|^  name:' | paste - -; kubectl kustomize overlays/dev | grep -A2 secretKeyRef | grep 'name: colis-db' | sort | uniq -c; kubectl kustomize overlays/dev | grep -B3 -A10 '^  name: api\$' | grep -E 'labels|part-of|environnement|name: api' | head -8"
H 04-appliquer "cd colis && d=\$(date +%s); $KK apply -k overlays/dev; $KD rollout status statefulset/postgres --timeout=180s >/dev/null; $KD wait --for=condition=Available deploy --all --timeout=300s >/dev/null; echo \"prêt en \$(( \$(date +%s)-d )) s\"; $KD get pods,cm,secret; sleep 3; curl -s -H 'Host: colis-dev.local' http://$IP/api/pret; echo; $KD get cronjob purge; $KD get deploy api -o jsonpath='{.metadata.labels}{\"\\n\"}{.spec.selector}{\"\\n\"}{.spec.template.spec.containers[0].image}{\"\\n\"}'; $KD exec deploy/api -- printenv COLIS_PURGE_JOURS"
H 05-config "cd colis && sed -i 's/  - COLIS_PURGE_JOURS=7/  - COLIS_PURGE_JOURS=14/' overlays/dev/kustomization.yaml; $KK diff -k overlays/dev | grep -E '^diff|^[-+] .*(colis-config|COLIS_PURGE)'; $KK apply -k overlays/dev | grep -v unchanged; $KD rollout status deploy/api --timeout=120s | tail -1; $KD get cm; $KD exec deploy/api -- printenv COLIS_PURGE_JOURS; $KD get sts postgres -o jsonpath='{.metadata.generation}{\"\\n\"}'; $KD get pod postgres-0 -o jsonpath='{.metadata.creationTimestamp} {.status.containerStatuses[0].restartCount}{\"\\n\"}'"
H 06-retour "cd colis && sed -i 's/  - COLIS_PURGE_JOURS=14/  - COLIS_PURGE_JOURS=7/' overlays/dev/kustomization.yaml; $KK apply -k overlays/dev | grep -E 'configmap|deployment'; $KD rollout status deploy/api --timeout=120s | tail -1; $KD exec deploy/api -- printenv COLIS_PURGE_JOURS; $KD get cm"
H 07-prod "cd colis && kubectl kustomize overlays/prod | grep -E 'image: .*colis/api' | sort | uniq -c; kubectl kustomize overlays/prod | python3 -c 'import sys,yaml
for d in yaml.safe_load_all(sys.stdin):
    if d and d[\"kind\"]==\"Deployment\" and d[\"metadata\"][\"name\"]==\"api\": print(d[\"spec\"][\"replicas\"], d[\"spec\"][\"template\"][\"spec\"][\"containers\"][0][\"resources\"])'; diff <(kubectl kustomize overlays/dev) <(kubectl kustomize overlays/prod) | grep -c '^[<>]'"
H 08-image-piege "cd colis && sed 's|^- name: host.minikube.internal:5001/colis/api   # le nom tel que la base l.a laissé|- name: colis-api|' overlays/prod/kustomization.yaml > /tmp/k.yaml && cp overlays/prod/kustomization.yaml overlays/prod/k.bak && cp /tmp/k.yaml overlays/prod/kustomization.yaml && grep -A2 '^images' overlays/prod/kustomization.yaml; kubectl kustomize overlays/prod | grep -E 'image: .*colis/api' | sort | uniq -c; cp overlays/prod/k.bak overlays/prod/kustomization.yaml; rm overlays/prod/k.bak /tmp/k.yaml"
H 09-dry-run "cd colis && $KK apply -k overlays/prod --dry-run=server 2>&1 | sort | uniq -c | sort -rn | head -3; $KK apply -f overlays/prod/namespace.yaml; $KK apply -k overlays/prod --dry-run=server; $KK delete namespace colis-prod"
H 10-helm "cd podinfo && kubectl kustomize . 2>&1 | tail -1; kubectl kustomize --enable-helm . | grep -E '^kind:|^  name:|replicas:|equipe|PODINFO_UI_MESSAGE|rendu par|helm.sh/hook:'; rm -rf charts"
H 11-prefixe "cd colis && mkdir -p overlays/essai && cp overlays/dev/secret.env overlays/essai/ && printf 'apiVersion: kustomize.config.k8s.io/v1beta1\nkind: Kustomization\nnamespace: colis-dev\nnamePrefix: essai-\nresources:\n- ../../base\nsecretGenerator:\n- name: colis-db\n  envs:\n  - secret.env\n' > overlays/essai/kustomization.yaml; R=\$(kubectl kustomize overlays/essai); echo \"\$R\" | python3 -c 'import sys,yaml
for d in yaml.safe_load_all(sys.stdin):
    if d and d[\"kind\"] in (\"Service\",\"StatefulSet\",\"HTTPRoute\"): print(d[\"kind\"], d[\"metadata\"][\"name\"])'; echo \"\$R\" | grep -E 'COLIS_REDIS|value: postgresql' | sort | uniq -c; echo \"\$R\" | grep -A1 serviceName; echo \"\$R\" | grep -A2 backendRefs | grep name:; kubectl kustomize /tmp 2>&1 | head -1; rm -rf overlays/essai"
