#!/usr/bin/env bash
# Chapitre 26 : les StatefulSets. Namespace « ch26 » (recréé). Remet Colis dans l'état du chapitre 25
# (PostgreSQL en Deployment sur la PVC postgres-donnees, images 2.0), puis le migre en StatefulSet
# sans perdre ses données et passe l'API et le worker en 2.1. Laisse Colis ainsi (http://192.168.49.100/).
cd "$(dirname "$0")"; O=$PWD/out/ch26; rm -rf $O; mkdir -p $O; cp -a ../kits/statefulset $O/m
export PATH=~/.local/opt/cours-k8s/bin:$PATH LC_ALL=C
K="kubectl --context minikube -n ch26"; KC="kubectl --context minikube -n colis"; KK="kubectl --context minikube"
H() { local n=$1; shift; echo "### $n : $*"; (cd $O/m && timeout 900 bash -c "$*") 2>&1 | grep -v '^W[0-9]' > $O/$n.txt; head -c 9000 $O/$n.txt; }
IP=192.168.49.100
$KK delete namespace ch26 --wait=true >/dev/null 2>&1; $KK create namespace ch26 >/dev/null

# --- Colis revient à l'état du chapitre 25
$KC delete statefulset/postgres deployment/postgres --ignore-not-found --wait=true >/dev/null
for pv in $($KK get pv -o json | jq -r '.items[] | select(.spec.claimRef.namespace=="colis" and (.spec.claimRef.name=="donnees-postgres-0" or .spec.claimRef.name=="postgres-donnees")) | .metadata.name'); do
  $KK patch pv $pv -p '{"spec":{"persistentVolumeReclaimPolicy":"Delete"}}' >/dev/null; done
$KC delete pvc donnees-postgres-0 postgres-donnees --ignore-not-found --wait=true >/dev/null
for pv in $($KK get pv -o json | jq -r '.items[] | select(.status.phase!="Bound" and (.spec.hostPath.path // "" | startswith("/tmp/hostpath-provisioner/colis/"))) | .metadata.name'); do d=$($KK get pv $pv -o jsonpath='{.spec.hostPath.path}'); $KK delete pv $pv >/dev/null; minikube ssh -- "sudo rm -rf $d" >/dev/null 2>&1; done
$KC delete service postgres --ignore-not-found >/dev/null
mkdir -p $O/ch24 && for f in 10-config 30-api 31-worker 50-purge; do sed 's|image: colis:2.0|image: host.minikube.internal:5001/colis/api:2.0|' ../kits/colis-k8s/$f.yaml > $O/ch24/$f.yaml; done
$KK apply -f ../kits/stockage/colis/20-postgres.yaml -f $O/ch24/10-config.yaml -f $O/ch24/30-api.yaml -f $O/ch24/31-worker.yaml >/dev/null
$KC rollout status deployment/postgres --timeout=180s >/dev/null
$KC rollout restart deployment/api deployment/worker >/dev/null; $KC rollout status deployment/api --timeout=180s >/dev/null; $KC rollout status deployment/worker --timeout=180s >/dev/null; sleep 5
curl -s -X POST http://$IP/api/colis -H 'Content-Type: application/json' -d '{"destinataire":"Katherine Johnson","depart":"Toulouse","arrivee":"Lille","poids_kg":1.8}' >/dev/null; sleep 4

H 01-deux-postgres "$K apply -f deux-postgres.yaml; sleep 45; $K get pods -l app=base; A=\$($K get pods -l app=base -o name | sed -n 1p); B=\$($K get pods -l app=base -o name | sed -n 2p); for p in \$A \$B; do echo \"== \$p\"; $K logs \$p --previous 2>/dev/null | grep -m1 'initdb: error'; $K logs \$p | tail -1; done; $K exec \$A -- psql -U postgres -c 'CREATE TABLE t (x int); INSERT INTO t VALUES (1), (2);'; $K exec \$B -- psql -U postgres -c 'SELECT count(*) FROM t;'; $K exec \$A -- head -1 /var/lib/postgresql/18/docker/postmaster.pid; $K delete -f deux-postgres.yaml --wait=true"
H 02-pile "d=\$(date +%s); $K apply -f pile.yaml; $K rollout status statefulset/pile --timeout=120s >/dev/null; echo \"prêt en \$(( \$(date +%s)-d )) s\"; $K get pods -l app=pile -o custom-columns='NOM:.metadata.name,CRÉÉ:.metadata.creationTimestamp,PRÊT:.status.conditions[?(@.type==\"Ready\")].lastTransitionTime'; $K get pvc; $K get events --field-selector involvedObject.kind=StatefulSet --sort-by=.metadata.resourceVersion -o custom-columns=RAISON:.reason,MESSAGE:.message"
H 03-dns "$K run client --image=busybox:1.37 --restart=Never -- sleep 3600 >/dev/null; $K wait --for=condition=Ready pod/client --timeout=60s >/dev/null; $K get service pile; $K get pods -l app=pile -o wide | cut -c1-75; $K exec client -- nslookup pile.ch26.svc.cluster.local. | grep -A1 '^Name'; $K exec client -- nslookup pile-1.pile.ch26.svc.cluster.local. | grep -A1 '^Name'; $K exec client -- wget -qO- http://pile-1.pile:8080/"
H 04-perte "$K get pod pile-1 -o jsonpath='{.metadata.uid} {.status.podIP}{\"\\n\"}'; $K delete pod pile-1; $K wait --for=condition=Ready pod/pile-1 --timeout=60s; $K get pod pile-1 -o jsonpath='{.metadata.uid} {.status.podIP} {.spec.volumes[0].persistentVolumeClaim.claimName}{\"\\n\"}'; sleep 2; $K exec client -- wget -qO- http://pile-1.pile:8080/; $K exec client -- nslookup pile-1.pile.ch26.svc.cluster.local. | grep -A1 '^Name'"
H 05-echelle "$K scale statefulset pile --replicas=1; sleep 12; $K get events --field-selector involvedObject.kind=StatefulSet,reason=SuccessfulDelete --sort-by=.metadata.resourceVersion -o custom-columns=MESSAGE:.message; $K get pods -l app=pile; $K get pvc; $K scale statefulset pile --replicas=3; $K rollout status statefulset/pile --timeout=120s >/dev/null; $K exec client -- wget -qO- http://pile-2.pile:8080/"
H 06-retention "$K patch statefulset pile -p '{\"spec\":{\"persistentVolumeClaimRetentionPolicy\":{\"whenScaled\":\"Delete\",\"whenDeleted\":\"Retain\"}}}'; $K scale statefulset pile --replicas=2; sleep 10; $K get pvc; $K scale statefulset pile --replicas=3; $K rollout status statefulset/pile --timeout=120s >/dev/null; $K exec client -- wget -qO- http://pile-2.pile:8080/"
H 07-maj "$K get statefulset pile -o jsonpath='{.spec.updateStrategy}{\" \"}{.spec.podManagementPolicy}{\"\\n\"}'; $K set env statefulset/pile VERSION=2; $K rollout status statefulset/pile --timeout=180s >/dev/null; $K get events --field-selector involvedObject.kind=StatefulSet --sort-by=.metadata.resourceVersion -o custom-columns=MESSAGE:.message | tail -6; $K get pods -l app=pile -o custom-columns='NOM:.metadata.name,RÉVISION:.metadata.labels.controller-revision-hash,CRÉÉ:.metadata.creationTimestamp'"
H 08-partition "$K patch statefulset pile -p '{\"spec\":{\"updateStrategy\":{\"rollingUpdate\":{\"partition\":2}}}}'; $K set env statefulset/pile VERSION=3; sleep 15; $K get pods -l app=pile -o custom-columns='NOM:.metadata.name,VERSION:.spec.containers[0].env[0].value,RÉVISION:.metadata.labels.controller-revision-hash'; $K get statefulset pile -o jsonpath='{.status.currentRevision} {.status.updateRevision} {.status.updatedReplicas}{\"\\n\"}'; $K patch statefulset pile -p '{\"spec\":{\"updateStrategy\":{\"rollingUpdate\":{\"partition\":0}}}}'; $K rollout status statefulset/pile --timeout=180s | tail -1; $K get pods -l app=pile -o custom-columns='NOM:.metadata.name,VERSION:.spec.containers[0].env[0].value'"
H 09-casse "$K set image statefulset/pile serveur=busybox:9.99; sleep 25; $K get pods -l app=pile; $K rollout undo statefulset/pile 2>&1 | grep -v Warning; sleep 45; $K get pods -l app=pile; $K get pod pile-2 -o jsonpath='{.spec.containers[0].image}{\"\\n\"}'; $K delete pod pile-2; $K wait --for=condition=Ready pod/pile-2 --timeout=60s; $K get pod pile-2 -o jsonpath='{.spec.containers[0].image}{\"\\n\"}'"
H 10-immuable "$K patch statefulset pile --type json -p '[{\"op\":\"replace\",\"path\":\"/spec/volumeClaimTemplates/0/spec/resources/requests/storage\",\"value\":\"20Mi\"}]' 2>&1 | sed 's/Invalid value: \\[.*\\]: field/Invalid value: [...]: field/'"
# --- Colis
H 11-colis-avant "$KC get deployment postgres; $KC get pvc; V=\$($KC get pvc postgres-donnees -o jsonpath='{.spec.volumeName}'); $KK get pv \$V; curl -s http://$IP/api/colis | jq -c '[.[] | {id, destinataire}]'"
H 12-service "sed -n '1,/^---/p' colis/20-postgres.yaml | head -n -1 | $KK apply -f -"
H 13-migration "V=\$($KC get pvc postgres-donnees -o jsonpath='{.spec.volumeName}'); echo \$V; $KK patch pv \$V -p '{\"spec\":{\"persistentVolumeReclaimPolicy\":\"Retain\"}}'; $KC delete deployment postgres; $KC delete service postgres; $KC delete pvc postgres-donnees; $KK get pv \$V; $KK patch pv \$V --type json -p '[{\"op\":\"remove\",\"path\":\"/spec/claimRef\"}]'; printf 'apiVersion: v1\nkind: PersistentVolumeClaim\nmetadata:\n  name: donnees-postgres-0\n  namespace: colis\nspec:\n  accessModes: [ReadWriteOnce]\n  resources:\n    requests:\n      storage: 1Gi\n  storageClassName: standard\n  volumeName: '\$V'\n' > reprise.yaml; cat reprise.yaml; $KK apply -f reprise.yaml; sleep 3; $KC get pvc; $KK apply -f colis/20-postgres.yaml; $KC rollout status statefulset/postgres --timeout=180s; $KC get pods -l app.kubernetes.io/name=postgres; $KC exec postgres-0 -- psql -U colis -d colis -tc 'SELECT id, destinataire FROM colis;'"
H 14-colis-21 "$KK apply -f colis/10-config.yaml -f colis/30-api.yaml -f colis/31-worker.yaml; $KC rollout status deployment/api --timeout=180s >/dev/null; $KC rollout status deployment/worker --timeout=180s >/dev/null; sleep 3; curl -s http://$IP/api/sante; echo; curl -s http://$IP/api/colis | jq -c '[.[] | {id, destinataire}]'; P=\$($KC get pods -l app.kubernetes.io/name=api -o name | head -1); $KC exec \$P -- python -c 'import socket; print(socket.gethostbyname_ex(\"postgres\")); print(socket.gethostbyname_ex(\"postgres-0.postgres\"))'; $KC get pod postgres-0 -o jsonpath='{.status.podIP}{\"\\n\"}'"
H 15-resilience "$KC get pods -l app.kubernetes.io/name=api; ( fin=\$((\$(date +%s)+75)); while [ \$(date +%s) -lt \$fin ]; do c=\$(curl -s -o /dev/null -m 2 -w '%{http_code}' http://$IP/api/colis); echo \"\$(date +%s.%N | cut -c1-14) \$c\"; sleep 0.2; done ) > charge.txt & sleep 5; t0=\$(date +%s.%N | cut -c1-14); echo \"suppression à \$t0\"; $KC delete pod postgres-0; wait; awk '{n[\$2]++} END {for (c in n) print c, n[c]}' charge.txt | sort; awk -v t0=\$t0 '\$2!=200 {if (!d) d=\$1; f=\$1} END {printf \"premier échec %.1f s après la suppression, dernier %.1f s après\\n\", d-t0, f-t0}' charge.txt; $KC get pods -l 'app.kubernetes.io/name in (api,worker,postgres)'; curl -s http://$IP/api/pret; echo"
H 16-purge "$KC delete pod purge --ignore-not-found; $KK apply -f colis/50-purge.yaml; $KC wait --for=jsonpath='{.status.phase}'=Succeeded pod/purge --timeout=90s; $KC logs purge"
