#!/usr/bin/env bash
# Chapitre 21 : configurer une application. Namespace « ch21 » (recréé), manifestes de kits/config.
cd "$(dirname "$0")"; O=$PWD/out/ch21; rm -rf $O; mkdir -p $O; cp -a ../kits/config $O/m
export PATH=~/.local/opt/cours-k8s/bin:$PATH LC_ALL=C
kubectl config use-context minikube >/dev/null
kubectl delete namespace ch21 --wait=true >/dev/null 2>&1; kubectl create namespace ch21 >/dev/null; kubectl config set-context --current --namespace=ch21 >/dev/null
H() { local n=$1; shift; echo "### $n : $*"; (cd $O/m && timeout 400 bash -c "$*") 2>&1 | grep -v '^W[0-9]' > $O/$n.txt; head -c 9000 $O/$n.txt; }
H 01-creer-cm "kubectl create configmap essai --from-literal=COULEUR=bleu --from-literal=TAILLE=12 --dry-run=client -o yaml; printf 'COULEUR=vert\nTAILLE=14\n' > reglages.env; kubectl create configmap essai-env --from-env-file=reglages.env --dry-run=client -o yaml | sed -n '/^data:/,/^kind/p'; kubectl create configmap essai-fichier --from-file=reglages.env --dry-run=client -o yaml | sed -n '/^data:/,/^kind/p'"
H 02-appliquer "kubectl apply -f configmap.yaml -f vitrine.yaml; kubectl rollout status deployment/vitrine --timeout=90s; kubectl get configmap vitrine-config; kubectl describe configmap vitrine-config | sed -n '1,20p'"
H 03-envfrom "P=\$(kubectl get pods -l app=vitrine -o name); kubectl exec \$P -- sh -c 'echo MESSAGE=\$MESSAGE; echo NIVEAU_LOG=\$NIVEAU_LOG; env | grep -A1 ^index'; kubectl get events --field-selector reason=InvalidEnvironmentVariableNames 2>&1 | head -2; kubectl exec \$P -- wget -q -O - http://localhost/; kubectl exec \$P -- ls -la /usr/share/nginx/html/"
H 04-lecteur "kubectl apply -f lecteur.yaml; kubectl wait --for=condition=Ready pod/lecteur --timeout=90s; sleep 3; kubectl logs lecteur | tail -2; kubectl exec lecteur -- sh -c 'echo NOM_DU_POD=\$NOM_DU_POD; echo MEMOIRE_MAX=\$MEMOIRE_MAX'; kubectl exec lecteur -- ls -la /config /config/..data/"
H 05-propagation "t0=\$(date +%s); kubectl patch configmap vitrine-config --type=merge -p '{\"data\":{\"MESSAGE\":\"Nouvelle version\"}}'; echo \"modification à \$(date +%T)\"; while [ \$((\$(date +%s)-t0)) -lt 150 ]; do if kubectl exec lecteur -- cat /config/MESSAGE | grep -q Nouvelle; then echo \"fichier mis à jour après \$((\$(date +%s)-t0)) s\"; break; fi; sleep 2; done; sleep 4; kubectl logs lecteur | tail -2; kubectl exec lecteur -- ls -la /config/"
H 06-restart "kubectl delete pod lecteur --wait=true >/dev/null; kubectl apply -f lecteur.yaml >/dev/null; kubectl wait --for=condition=Ready pod/lecteur --timeout=90s >/dev/null; sleep 3; kubectl logs lecteur | tail -1"
H 07-nginx-reload "kubectl patch configmap vitrine-config --type=merge -p '{\"data\":{\"index.html\":\"<h1>Colis v2</h1>\n\"}}'; P=\$(kubectl get pods -l app=vitrine -o name); for i in \$(seq 1 40); do r=\$(kubectl exec \$P -- wget -q -O - http://localhost/ | head -1); case \$r in *v2*) echo \"page mise à jour après environ \$((i*3)) s : \$r\"; break;; esac; sleep 3; done; kubectl rollout restart deployment/vitrine >/dev/null; kubectl rollout status deployment/vitrine --timeout=90s >/dev/null; kubectl exec \$(kubectl get pods -l app=vitrine --field-selector status.phase=Running -o name | head -1) -- sh -c 'echo MESSAGE=\$MESSAGE'"
H 08-cle-absente "kubectl run cle-absente --image=busybox:1.37 --restart=Never --overrides='{\"spec\":{\"containers\":[{\"name\":\"cle-absente\",\"image\":\"busybox:1.37\",\"command\":[\"sleep\",\"60\"],\"env\":[{\"name\":\"X\",\"valueFrom\":{\"configMapKeyRef\":{\"name\":\"vitrine-config\",\"key\":\"INEXISTANTE\"}}}]}]}}'; sleep 6; kubectl get pod cle-absente; kubectl get events --field-selector involvedObject.name=cle-absente,type=Warning -o custom-columns=MESSAGE:.message | tail -1"
H 09-cm-absente "kubectl run cm-absente --image=busybox:1.37 --restart=Never --overrides='{\"spec\":{\"volumes\":[{\"name\":\"c\",\"configMap\":{\"name\":\"nexiste-pas\"}}],\"containers\":[{\"name\":\"cm-absente\",\"image\":\"busybox:1.37\",\"command\":[\"sleep\",\"60\"],\"volumeMounts\":[{\"name\":\"c\",\"mountPath\":\"/c\"}]}]}}'; sleep 8; kubectl get pod cm-absente; kubectl get events --field-selector involvedObject.name=cm-absente,type=Warning -o custom-columns=MESSAGE:.message | tail -1"
H 10-immuable "kubectl create configmap figee --from-literal=A=1 --dry-run=client -o yaml | sed '/^kind/a immutable: true' | kubectl apply -f -; kubectl patch configmap figee --type=merge -p '{\"data\":{\"A\":\"2\"}}' 2>&1"
H 11-secret "kubectl apply -f secret-db.yaml; kubectl get secret colis-db; kubectl get secret colis-db -o yaml | sed -n '/^data:/,/^kind/p'; kubectl get secret colis-db -o jsonpath='{.data.POSTGRES_PASSWORD}' | base64 -d; echo"
H 11b-annotation "kubectl get secret colis-db -o jsonpath='{.metadata.annotations.kubectl\\.kubernetes\\.io/last-applied-configuration}'"
H 12-secret-pod "kubectl apply -f utilise-secret.yaml; kubectl wait --for=condition=Ready pod/utilise-secret --timeout=90s >/dev/null; kubectl exec utilise-secret -- sh -c 'echo \$POSTGRES_PASSWORD; ls -laL /run/secrets/colis-db/; cat /run/secrets/colis-db/POSTGRES_USER; echo; mount | grep colis-db'"
H 13-etcd "kubectl exec -n kube-system etcd-minikube -- etcdctl --endpoints=https://127.0.0.1:2379 --cacert=/var/lib/minikube/certs/etcd/ca.crt --cert=/var/lib/minikube/certs/etcd/server.crt --key=/var/lib/minikube/certs/etcd/server.key get /registry/secrets/ch21/colis-db --print-value-only | strings -n 5 | tail -6"
H 14-secret-docker "kubectl create secret docker-registry registre-prive --docker-server=registre.example --docker-username=colis --docker-password=secret123 --dry-run=client -o yaml | sed -n '/^data:/,/^type/p'; kubectl create secret docker-registry registre-prive --docker-server=registre.example --docker-username=colis --docker-password=secret123 --dry-run=client -o jsonpath='{.data.\\.dockerconfigjson}' | base64 -d; echo"
