#!/usr/bin/env bash
# Chapitre 23 : les ressources. Namespaces « ch23 » et « ch23-quota » (recréés), manifestes de kits/ressources.
cd "$(dirname "$0")"; O=$PWD/out/ch23; rm -rf $O; mkdir -p $O; cp -a ../kits/ressources $O/m
export PATH=~/.local/opt/cours-k8s/bin:$PATH LC_ALL=C
kubectl config use-context minikube >/dev/null
for ns in ch23 ch23-quota; do kubectl delete namespace $ns --wait=true >/dev/null 2>&1; done
kubectl create namespace ch23 >/dev/null; kubectl config set-context --current --namespace=ch23 >/dev/null
H() { local n=$1; shift; echo "### $n : $*"; (cd $O/m && timeout 400 bash -c "$*") 2>&1 | grep -v '^W[0-9]' > $O/$n.txt; head -c 9000 $O/$n.txt; }
H 01-noeud "kubectl get node minikube -o jsonpath='capacité : {.status.capacity.cpu} CPU, {.status.capacity.memory}{\"\n\"}allouable : {.status.allocatable.cpu} CPU, {.status.allocatable.memory}{\"\n\"}'; kubectl describe node minikube | sed -n '/Allocated resources/,/Events/p'"
H 02-gros "kubectl apply -f gros.yaml; sleep 8; kubectl get pods -l app=gros; P=\$(kubectl get pods -l app=gros --field-selector status.phase=Pending -o name | head -1); kubectl describe \$P | sed -n '/^Events:/,\$p' | cut -c1-220; kubectl describe node minikube | sed -n '/Allocated resources/,/Events/p'; kubectl delete -f gros.yaml --wait=true >/dev/null"
H 03-qos "kubectl apply -f qos.yaml; kubectl wait --for=condition=Ready pod/garanti pod/extensible pod/sans-garantie --timeout=90s >/dev/null; kubectl get pods -o custom-columns='NOM:.metadata.name,QOS:.status.qosClass'; for p in garanti extensible sans-garantie; do echo \"\$p : oom_score_adj=\$(kubectl exec \$p -- cat /proc/1/oom_score_adj) cpu.weight=\$(kubectl exec \$p -- cat /sys/fs/cgroup/cpu.weight) cpu.max=\$(kubectl exec \$p -- cat /sys/fs/cgroup/cpu.max) memory.max=\$(kubectl exec \$p -- cat /sys/fs/cgroup/memory.max)\"; done"
H 04-cgroup "U=\$(kubectl get pod extensible -o jsonpath='{.metadata.uid}' | tr - _); G=\$(kubectl get pod garanti -o jsonpath='{.metadata.uid}' | tr - _); echo extensible=\$U; echo garanti=\$G; minikube ssh -- \"cd /sys/fs/cgroup/kubepods.slice; ls -d kubepods-*; ls -d kubepods-burstable.slice/*-pod\${U}.slice; cat kubepods-pod\${G}.slice/cpu.max kubepods-pod\${G}.slice/memory.max\""
H 05-oom "kubectl apply -f gourmand-memoire.yaml; sleep 15; kubectl get pod gourmand-memoire; kubectl logs gourmand-memoire; kubectl get pod gourmand-memoire -o jsonpath='{.status.containerStatuses[0].state.terminated.reason} code={.status.containerStatuses[0].state.terminated.exitCode}{\"\n\"}'"
H 06-cpu "kubectl apply -f gourmand-cpu.yaml; kubectl wait --for=condition=Ready pod/gourmand-cpu --timeout=60s >/dev/null; sleep 70; kubectl top pod gourmand-cpu; kubectl exec gourmand-cpu -- sh -c 'cat /sys/fs/cgroup/cpu.max; grep -E \"nr_periods|nr_throttled|throttled_usec\" /sys/fs/cgroup/cpu.stat'"
H 07-disque "kubectl apply -f disque.yaml; sleep 40; kubectl get pod disque; kubectl get pod disque -o jsonpath='{.status.phase} {.status.reason}: {.status.message}{\"\n\"}'; kubectl get events --field-selector involvedObject.name=disque -o custom-columns=RAISON:.reason,MESSAGE:.message | tail -3 | cut -c1-200"
H 08-limitrange "kubectl create namespace ch23-quota >/dev/null; kubectl -n ch23-quota apply -f limitrange.yaml; kubectl -n ch23-quota describe limitrange bornes | tail -5; kubectl -n ch23-quota run nu --image=busybox:1.37 -- sleep 3600 >/dev/null; kubectl -n ch23-quota get pod nu -o jsonpath='{.spec.containers[0].resources}' | jq -c .; kubectl -n ch23-quota get pod nu -o jsonpath='{.metadata.annotations}' | jq -c .; kubectl -n ch23-quota run trop --image=busybox:1.37 --overrides='{\"spec\":{\"containers\":[{\"name\":\"trop\",\"image\":\"busybox:1.37\",\"command\":[\"sleep\",\"3600\"],\"resources\":{\"limits\":{\"cpu\":\"2\"}}}]}}' 2>&1"
H 09-quota "kubectl -n ch23-quota apply -f quota.yaml; sleep 2; kubectl -n ch23-quota describe resourcequota plafond | tail -7; for i in 1 2 3 4 5 6; do kubectl -n ch23-quota run p\$i --image=busybox:1.37 -- sleep 3600 2>&1 | tail -1; done; kubectl -n ch23-quota describe resourcequota plafond | tail -6"
H 10-quota-deploy "kubectl -n ch23-quota delete pods --all --wait=true >/dev/null; kubectl -n ch23-quota create deployment dix --image=busybox:1.37 --replicas=10 -- sleep 3600 >/dev/null; sleep 8; kubectl -n ch23-quota get deployment dix; kubectl -n ch23-quota get rs -l app=dix; kubectl -n ch23-quota describe rs -l app=dix | grep -m2 FailedCreate | cut -c1-230"
