#!/usr/bin/env bash
# Chapitre 20 : les Services. Namespace « ch20 » (recréé) ; addon metallb, plage 192.168.49.100-120 posée par metallb-plage.yaml (laissé actif).
cd "$(dirname "$0")"; O=$PWD/out/ch20; rm -rf $O; mkdir -p $O; cp -a ../kits/services $O/m
export PATH=~/.local/opt/cours-k8s/bin:$PATH
kubectl config use-context minikube >/dev/null
kubectl delete namespace ch20 --wait=true >/dev/null 2>&1; kubectl create namespace ch20 >/dev/null; kubectl config set-context --current --namespace=ch20 >/dev/null
H() { local n=$1; shift; echo "### $n : $*"; (cd $O/m && timeout 300 bash -c "$*") 2>&1 | grep -v '^W[0-9]' > $O/$n.txt; head -c 9000 $O/$n.txt; }
H 01-web "kubectl apply -f web.yaml; kubectl rollout status deployment/web --timeout=180s; kubectl get pods -o wide | cut -c1-110"
H 02-ip-ephemere "P=\$(kubectl get pods -l app=web -o name | head -1); kubectl get \$P -o jsonpath='{.metadata.name} {.status.podIP}{\"\n\"}'; kubectl delete \$P; kubectl rollout status deployment/web --timeout=60s >/dev/null; kubectl get pods -o wide | cut -c1-110"
H 03-service "kubectl apply -f service.yaml; kubectl get service web; kubectl get endpointslices -l kubernetes.io/service-name=web; kubectl get endpointslices -l kubernetes.io/service-name=web -o json | jq -r '.items[0].endpoints[] | \"\(.addresses[0]) \(.targetRef.name) ready=\(.conditions.ready)\"'"
H 04-repartition "kubectl run client --image=busybox:1.37 --restart=Never -- sleep 3600 >/dev/null; kubectl wait --for=condition=Ready pod/client --timeout=60s >/dev/null; kubectl exec client -- sh -c 'for i in \$(seq 1 30); do wget -q -O - http://web/hostname; echo; done' | sort | uniq -c"
H 05-dns "kubectl exec client -- cat /etc/resolv.conf; kubectl exec client -- nslookup web; kubectl exec client -- nslookup web.ch20.svc.cluster.local; kubectl -n default run client2 --image=busybox:1.37 --restart=Never --rm -i -- sh -c 'wget -q -T 3 -O - http://web/hostname; echo code=\$?; wget -q -T 3 -O - http://web.ch20/hostname; echo; echo code=\$?' 2>&1 | grep -vE 'client2|command prompt|recorded in container'"
H 06-env "kubectl exec client -- env | grep -E '^WEB_' | sort"
H 07-suivi "kubectl scale deployment web --replicas=1; sleep 5; kubectl get endpointslices -l kubernetes.io/service-name=web; kubectl scale deployment web --replicas=3; kubectl rollout status deployment/web --timeout=60s >/dev/null; sleep 2; kubectl get endpointslices -l kubernetes.io/service-name=web"
H 08-iptables "IP=\$(kubectl get svc web -o jsonpath='{.spec.clusterIP}'); echo clusterIP=\$IP; minikube ssh -- sudo iptables -t nat -S KUBE-SERVICES | grep 'ch20/web:http cluster IP'; C=\$(minikube ssh -- sudo iptables -t nat -S KUBE-SERVICES | grep 'ch20/web:http cluster IP' | grep -o 'KUBE-SVC-[A-Z0-9]*' | tr -d '\r'); minikube ssh -- sudo iptables -t nat -S \$C; S=\$(minikube ssh -- sudo iptables -t nat -S \$C | grep -o 'KUBE-SEP-[A-Z0-9]*' | head -1 | tr -d '\r'); minikube ssh -- sudo iptables -t nat -S \$S"
H 09-panne-selecteur "kubectl create service clusterip web-faute --tcp=80:8080 --dry-run=client -o yaml | sed 's/app: web-faute/app: webb/' | kubectl apply -f -; kubectl get endpointslices -l kubernetes.io/service-name=web-faute; kubectl exec client -- wget -q -T 3 -O - http://web-faute/hostname; echo code=\$?; kubectl describe service web-faute | grep -E 'Selector|Endpoints'"
H 10-panne-port "kubectl create service clusterip web-port --tcp=80:9090 --dry-run=client -o yaml | sed 's/app: web-port/app: web/' | kubectl apply -f -; kubectl get endpointslices -l kubernetes.io/service-name=web-port; kubectl exec client -- wget -q -T 3 -O - http://web-port/hostname; echo code=\$?"
H 11-nodeport "kubectl apply -f nodeport.yaml; sleep 3; kubectl get service web-nodeport; for i in 1 2 3; do curl -s -m 3 http://\$(minikube ip):30080/hostname; echo; done; minikube service web-nodeport -n ch20 --url"
H 12-loadbalancer "minikube addons enable metallb >/dev/null 2>&1; kubectl -n metallb-system rollout status deployment/controller --timeout=120s >/dev/null; kubectl apply -f metallb-plage.yaml; kubectl apply -f loadbalancer.yaml; sleep 8; kubectl get service web-lb; IP=\$(kubectl get service web-lb -o jsonpath='{.status.loadBalancer.ingress[0].ip}'); for i in 1 2 3 4; do curl -s -m 3 http://\$IP/hostname; echo; done"
H 13-headless "kubectl apply -f headless.yaml; kubectl get service web-headless; kubectl exec client -- nslookup web-headless; kubectl get pods -l app=web -o custom-columns=NOM:.metadata.name,IP:.status.podIP"
H 14-externalname "kubectl create service externalname documentation --external-name=kubernetes.io; kubectl get service documentation; kubectl exec client -- nslookup documentation.ch20.svc.cluster.local. | head -12"
H 15-tout "kubectl get services"
