apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: copies
spec:
  replicas: 3
  selector:
    matchLabels:
      app: copies
  template:
    metadata:
      labels:
        app: copies
    spec:
      containers:
      - name: nginx
        image: nginx:1.30-alpine
