apiVersion: v1
kind: Pod
metadata:
  name: lecteur
spec:
  containers:
  - name: lecteur
    image: busybox:1.37
    command: ["sh", "-c", "while true; do echo \"$(date +%T) env=$MESSAGE fichier=$(cat /config/MESSAGE) subpath=$(cat /etc/message)\"; sleep 2; done"]
    env:
    - name: MESSAGE
      valueFrom:
        configMapKeyRef:
          name: vitrine-config
          key: MESSAGE
    - name: NOM_DU_POD
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: MEMOIRE_MAX
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
    resources:
      limits:
        memory: 64Mi
    volumeMounts:
    - name: config
      mountPath: /config
    - name: config
      mountPath: /etc/message
      subPath: MESSAGE
  volumes:
  - name: config
    configMap:
      name: vitrine-config
