apiVersion: v1
kind: Pod
metadata:
  name: utilise-secret
spec:
  containers:
  - name: app
    image: busybox:1.37
    command: ["sleep", "3600"]
    env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: colis-db
          key: POSTGRES_PASSWORD
    volumeMounts:
    - name: identifiants
      mountPath: /run/secrets/colis-db
      readOnly: true
  volumes:
  - name: identifiants
    secret:
      secretName: colis-db
      defaultMode: 0400
