apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployeur
  namespace: colis
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployeur
  namespace: colis
rules:
- apiGroups: [apps]
  resources: [deployments]
  verbs: [get, list, watch]
- apiGroups: [apps]
  resources: [deployments]
  resourceNames: [api, web, worker]
  verbs: [patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployeur
  namespace: colis
subjects:
- kind: ServiceAccount
  name: deployeur
  namespace: colis
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployeur
