apiVersion: v1
kind: ConfigMap
metadata:
  name: colis-config
  namespace: colis-defi
  labels:
    app.kubernetes.io/part-of: colis
data:
  COLIS_REDIS: redis://redis:6379/0
  COLIS_VERSION: "2.0.0"
  COLIS_PURGE_JOURS: "30"
