apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: colis-defi
  labels:
    app.kubernetes.io/name: worker
    app.kubernetes.io/part-of: colis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: worker
        app.kubernetes.io/part-of: colis
    spec:
      containers:
      - name: worker
        image: host.minikube.internal:5001/colis/api:2.0
        imagePullPolicy: IfNotPresent
        command: ["python", "-m", "colis.worker"]
        envFrom:
        - configMapRef:
            name: colis-config
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: colis-db
              key: POSTGRES_PASSWORD
        - name: COLIS_DB
          value: postgresql://colis:$(POSTGRES_PASSWORD)@postgres:5432/colis
        resources:
          requests:
            cpu: 50m
            memory: 96Mi
          limits:
            memory: 192Mi
