apiVersion: v1
kind: Pod
metadata:
  name: malade
spec:
  containers:
  - name: agnhost
    image: registry.k8s.io/e2e-test-images/agnhost:2.61
    args: ["liveness"]
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      periodSeconds: 3
      failureThreshold: 3
