apiVersion: v1
kind: Pod
metadata:
  name: sleep-natif
spec:
  containers:
  - name: web
    image: registry.k8s.io/e2e-test-images/agnhost:2.61
    args: ["netexec", "--http-port=8080"]
    lifecycle:
      preStop:
        sleep:
          seconds: 5
