# Le même cluster, dont les journaux (WAL) partent en continu vers le stockage objet.
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: essai
  namespace: ch56
spec:
  instances: 3
  storage:
    size: 1Gi
  resources:
    requests: {cpu: 50m, memory: 128Mi}
    limits: {memory: 256Mi}
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: rustfs
