apiVersion: v1
kind: Pod
metadata:
  name: client-coffre
  namespace: ch42
spec:
  serviceAccountName: robot
  automountServiceAccountToken: false
  containers:
  - name: client
    image: busybox:1.37
    command: [sleep, infinity]
    volumeMounts:
    - name: jeton-coffre
      mountPath: /var/run/secrets/coffre
      readOnly: true
  volumes:
  - name: jeton-coffre
    projected:
      sources:
      - serviceAccountToken:
          path: jeton
          audience: coffre
          expirationSeconds: 600
