apiVersion: v1
kind: ServiceAccount
metadata:
  name: discret
  namespace: ch42
automountServiceAccountToken: false
---
apiVersion: v1
kind: Pod
metadata:
  name: sans-jeton
  namespace: ch42
spec:
  serviceAccountName: discret
  containers:
  - name: c
    image: busybox:1.37
    command: [sleep, infinity]
---
apiVersion: v1
kind: Pod
metadata:
  name: avec-jeton
  namespace: ch42
spec:
  serviceAccountName: discret
  automountServiceAccountToken: true
  containers:
  - name: c
    image: busybox:1.37
    command: [sleep, infinity]
